// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pool_1chan.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pool_1chan::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pool_1chan::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state1 = "1";
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state2 = "10";
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state3 = "100";
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state4 = "1000";
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state5 = "10000";
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state6 = "100000";
const sc_lv<7> max_pool_1chan::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> max_pool_1chan::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pool_1chan::ap_const_lv32_3 = "11";
const sc_lv<32> max_pool_1chan::ap_const_lv32_4 = "100";
const sc_lv<32> max_pool_1chan::ap_const_lv32_5 = "101";
const sc_lv<32> max_pool_1chan::ap_const_lv32_1 = "1";
const sc_lv<1> max_pool_1chan::ap_const_lv1_1 = "1";
const sc_lv<32> max_pool_1chan::ap_const_lv32_2 = "10";
const sc_lv<1> max_pool_1chan::ap_const_lv1_0 = "0";
const sc_lv<5> max_pool_1chan::ap_const_lv5_0 = "00000";
const sc_lv<32> max_pool_1chan::ap_const_lv32_6 = "110";
const sc_lv<32> max_pool_1chan::ap_const_lv32_17 = "10111";
const sc_lv<32> max_pool_1chan::ap_const_lv32_2F = "101111";
const sc_lv<5> max_pool_1chan::ap_const_lv5_1C = "11100";
const sc_lv<2> max_pool_1chan::ap_const_lv2_0 = "00";
const sc_lv<5> max_pool_1chan::ap_const_lv5_1 = "1";
const sc_lv<5> max_pool_1chan::ap_const_lv5_2 = "10";
const sc_lv<23> max_pool_1chan::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<4> max_pool_1chan::ap_const_lv4_0 = "0000";
const sc_lv<32> max_pool_1chan::ap_const_lv32_E = "1110";
const bool max_pool_1chan::ap_const_boolean_1 = true;

max_pool_1chan::max_pool_1chan(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_181_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_181_p2 );

    SC_METHOD(thread_grp_fu_143_p4);
    sensitive << ( in_image_V_q0 );

    SC_METHOD(thread_i_5_fu_309_p2);
    sensitive << ( i_reg_120 );

    SC_METHOD(thread_in_image_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_55_cast_fu_268_p1 );
    sensitive << ( tmp_56_cast_fu_315_p1 );

    SC_METHOD(thread_in_image_V_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_57_cast_fu_293_p1 );
    sensitive << ( tmp_58_cast_fu_333_p1 );

    SC_METHOD(thread_in_image_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in_image_V_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_j_5_fu_303_p2);
    sensitive << ( j_reg_132 );

    SC_METHOD(thread_max_V_8_fu_337_p3);
    sensitive << ( reg_163 );
    sensitive << ( reg_167 );
    sensitive << ( tmp_34_reg_547 );

    SC_METHOD(thread_max_V_9_fu_358_p3);
    sensitive << ( reg_163 );
    sensitive << ( max_V_8_reg_557 );
    sensitive << ( tmp_36_reg_562 );

    SC_METHOD(thread_out_image_V_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_63_cast_fu_431_p1 );

    SC_METHOD(thread_out_image_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_image_V_d0);
    sensitive << ( reg_167 );
    sensitive << ( max_V_9_reg_567 );
    sensitive << ( tmp_38_reg_572 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_image_V_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_p_s_fu_462_p3);
    sensitive << ( y_1_fu_436_p2 );
    sensitive << ( tmp_40_fu_442_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_243_p1);
    sensitive << ( tmp_46_fu_235_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_195_p1);
    sensitive << ( tmp_42_fu_187_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_207_p1);
    sensitive << ( tmp_43_fu_199_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_399_p3);
    sensitive << ( tmp_2_fu_395_p1 );

    SC_METHOD(thread_p_shl5_cast_fu_411_p3);
    sensitive << ( tmp_3_fu_407_p1 );

    SC_METHOD(thread_p_shl_cast_fu_231_p1);
    sensitive << ( tmp_45_fu_223_p3 );

    SC_METHOD(thread_p_x_1_fu_454_p3);
    sensitive << ( x_fu_62 );
    sensitive << ( tmp_40_fu_442_p2 );
    sensitive << ( x_1_fu_448_p2 );

    SC_METHOD(thread_tmp_1_fu_391_p1);
    sensitive << ( y_fu_58 );

    SC_METHOD(thread_tmp_28_fu_217_p2);
    sensitive << ( i_reg_120 );

    SC_METHOD(thread_tmp_29_fu_253_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_reg_132 );

    SC_METHOD(thread_tmp_2_fu_395_p1);
    sensitive << ( x_fu_62 );

    SC_METHOD(thread_tmp_30_cast_fu_259_p1);
    sensitive << ( j_reg_132 );

    SC_METHOD(thread_tmp_31_fu_278_p2);
    sensitive << ( j_reg_132 );

    SC_METHOD(thread_tmp_32_cast_fu_284_p1);
    sensitive << ( tmp_31_fu_278_p2 );

    SC_METHOD(thread_tmp_33_fu_319_p3);
    sensitive << ( grp_fu_143_p4 );

    SC_METHOD(thread_tmp_34_fu_327_p2);
    sensitive << ( in_image_V_q1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_33_fu_319_p3 );

    SC_METHOD(thread_tmp_35_fu_344_p3);
    sensitive << ( max_V_8_fu_337_p3 );

    SC_METHOD(thread_tmp_36_fu_352_p2);
    sensitive << ( in_image_V_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_35_fu_344_p3 );

    SC_METHOD(thread_tmp_37_fu_364_p3);
    sensitive << ( max_V_9_fu_358_p3 );

    SC_METHOD(thread_tmp_38_fu_372_p2);
    sensitive << ( in_image_V_q1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_37_fu_364_p3 );

    SC_METHOD(thread_tmp_3_fu_407_p1);
    sensitive << ( x_fu_62 );

    SC_METHOD(thread_tmp_40_fu_442_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( y_1_fu_436_p2 );

    SC_METHOD(thread_tmp_42_fu_187_p3);
    sensitive << ( i_reg_120 );

    SC_METHOD(thread_tmp_43_fu_199_p3);
    sensitive << ( i_reg_120 );

    SC_METHOD(thread_tmp_44_fu_211_p2);
    sensitive << ( p_shl2_cast_fu_195_p1 );
    sensitive << ( p_shl3_cast_fu_207_p1 );

    SC_METHOD(thread_tmp_45_fu_223_p3);
    sensitive << ( tmp_28_fu_217_p2 );

    SC_METHOD(thread_tmp_46_fu_235_p3);
    sensitive << ( tmp_28_fu_217_p2 );

    SC_METHOD(thread_tmp_47_fu_247_p2);
    sensitive << ( p_shl_cast_fu_231_p1 );
    sensitive << ( p_shl1_cast_fu_243_p1 );

    SC_METHOD(thread_tmp_48_fu_263_p2);
    sensitive << ( tmp_44_reg_497 );
    sensitive << ( tmp_30_cast_fu_259_p1 );

    SC_METHOD(thread_tmp_49_fu_273_p2);
    sensitive << ( tmp_47_reg_503 );
    sensitive << ( tmp_30_cast_fu_259_p1 );

    SC_METHOD(thread_tmp_50_fu_288_p2);
    sensitive << ( tmp_44_reg_497 );
    sensitive << ( tmp_32_cast_fu_284_p1 );

    SC_METHOD(thread_tmp_51_fu_298_p2);
    sensitive << ( tmp_47_reg_503 );
    sensitive << ( tmp_32_cast_fu_284_p1 );

    SC_METHOD(thread_tmp_52_fu_419_p2);
    sensitive << ( p_shl4_cast_fu_399_p3 );
    sensitive << ( p_shl5_cast_fu_411_p3 );

    SC_METHOD(thread_tmp_53_fu_425_p2);
    sensitive << ( tmp_1_fu_391_p1 );
    sensitive << ( tmp_52_fu_419_p2 );

    SC_METHOD(thread_tmp_55_cast_fu_268_p1);
    sensitive << ( tmp_48_fu_263_p2 );

    SC_METHOD(thread_tmp_56_cast_fu_315_p1);
    sensitive << ( tmp_49_reg_517 );

    SC_METHOD(thread_tmp_57_cast_fu_293_p1);
    sensitive << ( tmp_50_fu_288_p2 );

    SC_METHOD(thread_tmp_58_cast_fu_333_p1);
    sensitive << ( tmp_51_reg_527 );

    SC_METHOD(thread_tmp_63_cast_fu_431_p1);
    sensitive << ( tmp_53_fu_425_p2 );

    SC_METHOD(thread_tmp_fu_181_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_120 );

    SC_METHOD(thread_x_1_fu_448_p2);
    sensitive << ( x_fu_62 );

    SC_METHOD(thread_y_1_fu_436_p2);
    sensitive << ( y_fu_58 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_181_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_29_fu_253_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pool_1chan_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_image_V_address0, "(port)in_image_V_address0");
    sc_trace(mVcdFile, in_image_V_ce0, "(port)in_image_V_ce0");
    sc_trace(mVcdFile, in_image_V_q0, "(port)in_image_V_q0");
    sc_trace(mVcdFile, in_image_V_address1, "(port)in_image_V_address1");
    sc_trace(mVcdFile, in_image_V_ce1, "(port)in_image_V_ce1");
    sc_trace(mVcdFile, in_image_V_q1, "(port)in_image_V_q1");
    sc_trace(mVcdFile, out_image_V_address0, "(port)out_image_V_address0");
    sc_trace(mVcdFile, out_image_V_ce0, "(port)out_image_V_ce0");
    sc_trace(mVcdFile, out_image_V_we0, "(port)out_image_V_we0");
    sc_trace(mVcdFile, out_image_V_d0, "(port)out_image_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_143_p4, "grp_fu_143_p4");
    sc_trace(mVcdFile, reg_163, "reg_163");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, reg_167, "reg_167");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_44_fu_211_p2, "tmp_44_fu_211_p2");
    sc_trace(mVcdFile, tmp_44_reg_497, "tmp_44_reg_497");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_181_p2, "tmp_fu_181_p2");
    sc_trace(mVcdFile, tmp_47_fu_247_p2, "tmp_47_fu_247_p2");
    sc_trace(mVcdFile, tmp_47_reg_503, "tmp_47_reg_503");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_29_fu_253_p2, "tmp_29_fu_253_p2");
    sc_trace(mVcdFile, tmp_49_fu_273_p2, "tmp_49_fu_273_p2");
    sc_trace(mVcdFile, tmp_49_reg_517, "tmp_49_reg_517");
    sc_trace(mVcdFile, tmp_51_fu_298_p2, "tmp_51_fu_298_p2");
    sc_trace(mVcdFile, tmp_51_reg_527, "tmp_51_reg_527");
    sc_trace(mVcdFile, j_5_fu_303_p2, "j_5_fu_303_p2");
    sc_trace(mVcdFile, j_5_reg_532, "j_5_reg_532");
    sc_trace(mVcdFile, i_5_fu_309_p2, "i_5_fu_309_p2");
    sc_trace(mVcdFile, tmp_34_fu_327_p2, "tmp_34_fu_327_p2");
    sc_trace(mVcdFile, tmp_34_reg_547, "tmp_34_reg_547");
    sc_trace(mVcdFile, max_V_8_fu_337_p3, "max_V_8_fu_337_p3");
    sc_trace(mVcdFile, max_V_8_reg_557, "max_V_8_reg_557");
    sc_trace(mVcdFile, tmp_36_fu_352_p2, "tmp_36_fu_352_p2");
    sc_trace(mVcdFile, tmp_36_reg_562, "tmp_36_reg_562");
    sc_trace(mVcdFile, max_V_9_fu_358_p3, "max_V_9_fu_358_p3");
    sc_trace(mVcdFile, max_V_9_reg_567, "max_V_9_reg_567");
    sc_trace(mVcdFile, tmp_38_fu_372_p2, "tmp_38_fu_372_p2");
    sc_trace(mVcdFile, tmp_38_reg_572, "tmp_38_reg_572");
    sc_trace(mVcdFile, i_reg_120, "i_reg_120");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, j_reg_132, "j_reg_132");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_55_cast_fu_268_p1, "tmp_55_cast_fu_268_p1");
    sc_trace(mVcdFile, tmp_57_cast_fu_293_p1, "tmp_57_cast_fu_293_p1");
    sc_trace(mVcdFile, tmp_56_cast_fu_315_p1, "tmp_56_cast_fu_315_p1");
    sc_trace(mVcdFile, tmp_58_cast_fu_333_p1, "tmp_58_cast_fu_333_p1");
    sc_trace(mVcdFile, tmp_63_cast_fu_431_p1, "tmp_63_cast_fu_431_p1");
    sc_trace(mVcdFile, y_fu_58, "y_fu_58");
    sc_trace(mVcdFile, p_s_fu_462_p3, "p_s_fu_462_p3");
    sc_trace(mVcdFile, x_fu_62, "x_fu_62");
    sc_trace(mVcdFile, p_x_1_fu_454_p3, "p_x_1_fu_454_p3");
    sc_trace(mVcdFile, tmp_42_fu_187_p3, "tmp_42_fu_187_p3");
    sc_trace(mVcdFile, tmp_43_fu_199_p3, "tmp_43_fu_199_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_195_p1, "p_shl2_cast_fu_195_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_207_p1, "p_shl3_cast_fu_207_p1");
    sc_trace(mVcdFile, tmp_28_fu_217_p2, "tmp_28_fu_217_p2");
    sc_trace(mVcdFile, tmp_45_fu_223_p3, "tmp_45_fu_223_p3");
    sc_trace(mVcdFile, tmp_46_fu_235_p3, "tmp_46_fu_235_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_231_p1, "p_shl_cast_fu_231_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_243_p1, "p_shl1_cast_fu_243_p1");
    sc_trace(mVcdFile, tmp_30_cast_fu_259_p1, "tmp_30_cast_fu_259_p1");
    sc_trace(mVcdFile, tmp_48_fu_263_p2, "tmp_48_fu_263_p2");
    sc_trace(mVcdFile, tmp_31_fu_278_p2, "tmp_31_fu_278_p2");
    sc_trace(mVcdFile, tmp_32_cast_fu_284_p1, "tmp_32_cast_fu_284_p1");
    sc_trace(mVcdFile, tmp_50_fu_288_p2, "tmp_50_fu_288_p2");
    sc_trace(mVcdFile, tmp_33_fu_319_p3, "tmp_33_fu_319_p3");
    sc_trace(mVcdFile, tmp_35_fu_344_p3, "tmp_35_fu_344_p3");
    sc_trace(mVcdFile, tmp_37_fu_364_p3, "tmp_37_fu_364_p3");
    sc_trace(mVcdFile, tmp_2_fu_395_p1, "tmp_2_fu_395_p1");
    sc_trace(mVcdFile, tmp_3_fu_407_p1, "tmp_3_fu_407_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_399_p3, "p_shl4_cast_fu_399_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_411_p3, "p_shl5_cast_fu_411_p3");
    sc_trace(mVcdFile, tmp_1_fu_391_p1, "tmp_1_fu_391_p1");
    sc_trace(mVcdFile, tmp_52_fu_419_p2, "tmp_52_fu_419_p2");
    sc_trace(mVcdFile, tmp_53_fu_425_p2, "tmp_53_fu_425_p2");
    sc_trace(mVcdFile, y_1_fu_436_p2, "y_1_fu_436_p2");
    sc_trace(mVcdFile, tmp_40_fu_442_p2, "tmp_40_fu_442_p2");
    sc_trace(mVcdFile, x_1_fu_448_p2, "x_1_fu_448_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

max_pool_1chan::~max_pool_1chan() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void max_pool_1chan::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(tmp_fu_181_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(tmp_29_fu_253_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        i_reg_120 = i_5_fu_309_p2.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_120 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_reg_132 = j_5_reg_532.read();
    } else if ((esl_seteq<1,1,1>(tmp_fu_181_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_132 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_fu_62 = p_x_1_fu_454_p3.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        x_fu_62 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_fu_58 = p_s_fu_462_p3.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        y_fu_58 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(tmp_29_fu_253_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        j_5_reg_532 = j_5_fu_303_p2.read();
        tmp_49_reg_517 = tmp_49_fu_273_p2.read();
        tmp_51_reg_527 = tmp_51_fu_298_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        max_V_8_reg_557 = max_V_8_fu_337_p3.read();
        tmp_36_reg_562 = tmp_36_fu_352_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        max_V_9_reg_567 = max_V_9_fu_358_p3.read();
        tmp_38_reg_572 = tmp_38_fu_372_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        reg_163 = in_image_V_q0.read().range(47, 23);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        reg_167 = in_image_V_q1.read().range(47, 23);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp_34_reg_547 = tmp_34_fu_327_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_fu_181_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_44_reg_497 = tmp_44_fu_211_p2.read();
        tmp_47_reg_503 = tmp_47_fu_247_p2.read();
    }
}

void max_pool_1chan::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pool_1chan::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void max_pool_1chan::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void max_pool_1chan::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void max_pool_1chan::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void max_pool_1chan::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void max_pool_1chan::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void max_pool_1chan::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void max_pool_1chan::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_fu_181_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void max_pool_1chan::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pool_1chan::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_fu_181_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pool_1chan::thread_grp_fu_143_p4() {
    grp_fu_143_p4 = in_image_V_q0.read().range(47, 23);
}

void max_pool_1chan::thread_i_5_fu_309_p2() {
    i_5_fu_309_p2 = (!i_reg_120.read().is_01() || !ap_const_lv5_2.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_120.read()) + sc_biguint<5>(ap_const_lv5_2));
}

void max_pool_1chan::thread_in_image_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_image_V_address0 =  (sc_lv<10>) (tmp_56_cast_fu_315_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in_image_V_address0 =  (sc_lv<10>) (tmp_55_cast_fu_268_p1.read());
    } else {
        in_image_V_address0 = "XXXXXXXXXX";
    }
}

void max_pool_1chan::thread_in_image_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        in_image_V_address1 =  (sc_lv<10>) (tmp_58_cast_fu_333_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        in_image_V_address1 =  (sc_lv<10>) (tmp_57_cast_fu_293_p1.read());
    } else {
        in_image_V_address1 = "XXXXXXXXXX";
    }
}

void max_pool_1chan::thread_in_image_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        in_image_V_ce0 = ap_const_logic_1;
    } else {
        in_image_V_ce0 = ap_const_logic_0;
    }
}

void max_pool_1chan::thread_in_image_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        in_image_V_ce1 = ap_const_logic_1;
    } else {
        in_image_V_ce1 = ap_const_logic_0;
    }
}

void max_pool_1chan::thread_j_5_fu_303_p2() {
    j_5_fu_303_p2 = (!ap_const_lv5_2.is_01() || !j_reg_132.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_2) + sc_biguint<5>(j_reg_132.read()));
}

void max_pool_1chan::thread_max_V_8_fu_337_p3() {
    max_V_8_fu_337_p3 = (!tmp_34_reg_547.read()[0].is_01())? sc_lv<25>(): ((tmp_34_reg_547.read()[0].to_bool())? reg_167.read(): reg_163.read());
}

void max_pool_1chan::thread_max_V_9_fu_358_p3() {
    max_V_9_fu_358_p3 = (!tmp_36_reg_562.read()[0].is_01())? sc_lv<25>(): ((tmp_36_reg_562.read()[0].to_bool())? reg_163.read(): max_V_8_reg_557.read());
}

void max_pool_1chan::thread_out_image_V_address0() {
    out_image_V_address0 =  (sc_lv<8>) (tmp_63_cast_fu_431_p1.read());
}

void max_pool_1chan::thread_out_image_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        out_image_V_ce0 = ap_const_logic_1;
    } else {
        out_image_V_ce0 = ap_const_logic_0;
    }
}

void max_pool_1chan::thread_out_image_V_d0() {
    out_image_V_d0 = (!tmp_38_reg_572.read()[0].is_01())? sc_lv<25>(): ((tmp_38_reg_572.read()[0].to_bool())? reg_167.read(): max_V_9_reg_567.read());
}

void max_pool_1chan::thread_out_image_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        out_image_V_we0 = ap_const_logic_1;
    } else {
        out_image_V_we0 = ap_const_logic_0;
    }
}

void max_pool_1chan::thread_p_s_fu_462_p3() {
    p_s_fu_462_p3 = (!tmp_40_fu_442_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_40_fu_442_p2.read()[0].to_bool())? ap_const_lv32_0: y_1_fu_436_p2.read());
}

void max_pool_1chan::thread_p_shl1_cast_fu_243_p1() {
    p_shl1_cast_fu_243_p1 = esl_zext<11,7>(tmp_46_fu_235_p3.read());
}

void max_pool_1chan::thread_p_shl2_cast_fu_195_p1() {
    p_shl2_cast_fu_195_p1 = esl_zext<11,10>(tmp_42_fu_187_p3.read());
}

void max_pool_1chan::thread_p_shl3_cast_fu_207_p1() {
    p_shl3_cast_fu_207_p1 = esl_zext<11,7>(tmp_43_fu_199_p3.read());
}

void max_pool_1chan::thread_p_shl4_cast_fu_399_p3() {
    p_shl4_cast_fu_399_p3 = esl_concat<5,4>(tmp_2_fu_395_p1.read(), ap_const_lv4_0);
}

void max_pool_1chan::thread_p_shl5_cast_fu_411_p3() {
    p_shl5_cast_fu_411_p3 = esl_concat<8,1>(tmp_3_fu_407_p1.read(), ap_const_lv1_0);
}

void max_pool_1chan::thread_p_shl_cast_fu_231_p1() {
    p_shl_cast_fu_231_p1 = esl_zext<11,10>(tmp_45_fu_223_p3.read());
}

void max_pool_1chan::thread_p_x_1_fu_454_p3() {
    p_x_1_fu_454_p3 = (!tmp_40_fu_442_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_40_fu_442_p2.read()[0].to_bool())? x_1_fu_448_p2.read(): x_fu_62.read());
}

void max_pool_1chan::thread_tmp_1_fu_391_p1() {
    tmp_1_fu_391_p1 = y_fu_58.read().range(9-1, 0);
}

void max_pool_1chan::thread_tmp_28_fu_217_p2() {
    tmp_28_fu_217_p2 = (i_reg_120.read() | ap_const_lv5_1);
}

void max_pool_1chan::thread_tmp_29_fu_253_p2() {
    tmp_29_fu_253_p2 = (!j_reg_132.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): (sc_biguint<5>(j_reg_132.read()) < sc_biguint<5>(ap_const_lv5_1C));
}

void max_pool_1chan::thread_tmp_2_fu_395_p1() {
    tmp_2_fu_395_p1 = x_fu_62.read().range(5-1, 0);
}

void max_pool_1chan::thread_tmp_30_cast_fu_259_p1() {
    tmp_30_cast_fu_259_p1 = esl_zext<11,5>(j_reg_132.read());
}

void max_pool_1chan::thread_tmp_31_fu_278_p2() {
    tmp_31_fu_278_p2 = (j_reg_132.read() | ap_const_lv5_1);
}

void max_pool_1chan::thread_tmp_32_cast_fu_284_p1() {
    tmp_32_cast_fu_284_p1 = esl_zext<11,5>(tmp_31_fu_278_p2.read());
}

void max_pool_1chan::thread_tmp_33_fu_319_p3() {
    tmp_33_fu_319_p3 = esl_concat<25,23>(grp_fu_143_p4.read(), ap_const_lv23_0);
}

void max_pool_1chan::thread_tmp_34_fu_327_p2() {
    tmp_34_fu_327_p2 = (!in_image_V_q1.read().is_01() || !tmp_33_fu_319_p3.read().is_01())? sc_lv<1>(): (sc_bigint<48>(in_image_V_q1.read()) > sc_bigint<48>(tmp_33_fu_319_p3.read()));
}

void max_pool_1chan::thread_tmp_35_fu_344_p3() {
    tmp_35_fu_344_p3 = esl_concat<25,23>(max_V_8_fu_337_p3.read(), ap_const_lv23_0);
}

void max_pool_1chan::thread_tmp_36_fu_352_p2() {
    tmp_36_fu_352_p2 = (!in_image_V_q0.read().is_01() || !tmp_35_fu_344_p3.read().is_01())? sc_lv<1>(): (sc_bigint<48>(in_image_V_q0.read()) > sc_bigint<48>(tmp_35_fu_344_p3.read()));
}

void max_pool_1chan::thread_tmp_37_fu_364_p3() {
    tmp_37_fu_364_p3 = esl_concat<25,23>(max_V_9_fu_358_p3.read(), ap_const_lv23_0);
}

void max_pool_1chan::thread_tmp_38_fu_372_p2() {
    tmp_38_fu_372_p2 = (!in_image_V_q1.read().is_01() || !tmp_37_fu_364_p3.read().is_01())? sc_lv<1>(): (sc_bigint<48>(in_image_V_q1.read()) > sc_bigint<48>(tmp_37_fu_364_p3.read()));
}

void max_pool_1chan::thread_tmp_3_fu_407_p1() {
    tmp_3_fu_407_p1 = x_fu_62.read().range(8-1, 0);
}

void max_pool_1chan::thread_tmp_40_fu_442_p2() {
    tmp_40_fu_442_p2 = (!y_1_fu_436_p2.read().is_01() || !ap_const_lv32_E.is_01())? sc_lv<1>(): sc_lv<1>(y_1_fu_436_p2.read() == ap_const_lv32_E);
}

void max_pool_1chan::thread_tmp_42_fu_187_p3() {
    tmp_42_fu_187_p3 = esl_concat<5,5>(i_reg_120.read(), ap_const_lv5_0);
}

void max_pool_1chan::thread_tmp_43_fu_199_p3() {
    tmp_43_fu_199_p3 = esl_concat<5,2>(i_reg_120.read(), ap_const_lv2_0);
}

void max_pool_1chan::thread_tmp_44_fu_211_p2() {
    tmp_44_fu_211_p2 = (!p_shl2_cast_fu_195_p1.read().is_01() || !p_shl3_cast_fu_207_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl2_cast_fu_195_p1.read()) - sc_biguint<11>(p_shl3_cast_fu_207_p1.read()));
}

void max_pool_1chan::thread_tmp_45_fu_223_p3() {
    tmp_45_fu_223_p3 = esl_concat<5,5>(tmp_28_fu_217_p2.read(), ap_const_lv5_0);
}

void max_pool_1chan::thread_tmp_46_fu_235_p3() {
    tmp_46_fu_235_p3 = esl_concat<5,2>(tmp_28_fu_217_p2.read(), ap_const_lv2_0);
}

void max_pool_1chan::thread_tmp_47_fu_247_p2() {
    tmp_47_fu_247_p2 = (!p_shl_cast_fu_231_p1.read().is_01() || !p_shl1_cast_fu_243_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_231_p1.read()) - sc_biguint<11>(p_shl1_cast_fu_243_p1.read()));
}

void max_pool_1chan::thread_tmp_48_fu_263_p2() {
    tmp_48_fu_263_p2 = (!tmp_30_cast_fu_259_p1.read().is_01() || !tmp_44_reg_497.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_30_cast_fu_259_p1.read()) + sc_biguint<11>(tmp_44_reg_497.read()));
}

void max_pool_1chan::thread_tmp_49_fu_273_p2() {
    tmp_49_fu_273_p2 = (!tmp_30_cast_fu_259_p1.read().is_01() || !tmp_47_reg_503.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_30_cast_fu_259_p1.read()) + sc_biguint<11>(tmp_47_reg_503.read()));
}

void max_pool_1chan::thread_tmp_50_fu_288_p2() {
    tmp_50_fu_288_p2 = (!tmp_32_cast_fu_284_p1.read().is_01() || !tmp_44_reg_497.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_32_cast_fu_284_p1.read()) + sc_biguint<11>(tmp_44_reg_497.read()));
}

void max_pool_1chan::thread_tmp_51_fu_298_p2() {
    tmp_51_fu_298_p2 = (!tmp_32_cast_fu_284_p1.read().is_01() || !tmp_47_reg_503.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_32_cast_fu_284_p1.read()) + sc_biguint<11>(tmp_47_reg_503.read()));
}

void max_pool_1chan::thread_tmp_52_fu_419_p2() {
    tmp_52_fu_419_p2 = (!p_shl4_cast_fu_399_p3.read().is_01() || !p_shl5_cast_fu_411_p3.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl4_cast_fu_399_p3.read()) - sc_biguint<9>(p_shl5_cast_fu_411_p3.read()));
}

void max_pool_1chan::thread_tmp_53_fu_425_p2() {
    tmp_53_fu_425_p2 = (!tmp_1_fu_391_p1.read().is_01() || !tmp_52_fu_419_p2.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_1_fu_391_p1.read()) + sc_biguint<9>(tmp_52_fu_419_p2.read()));
}

void max_pool_1chan::thread_tmp_55_cast_fu_268_p1() {
    tmp_55_cast_fu_268_p1 = esl_sext<64,11>(tmp_48_fu_263_p2.read());
}

void max_pool_1chan::thread_tmp_56_cast_fu_315_p1() {
    tmp_56_cast_fu_315_p1 = esl_sext<64,11>(tmp_49_reg_517.read());
}

void max_pool_1chan::thread_tmp_57_cast_fu_293_p1() {
    tmp_57_cast_fu_293_p1 = esl_sext<64,11>(tmp_50_fu_288_p2.read());
}

void max_pool_1chan::thread_tmp_58_cast_fu_333_p1() {
    tmp_58_cast_fu_333_p1 = esl_sext<64,11>(tmp_51_reg_527.read());
}

void max_pool_1chan::thread_tmp_63_cast_fu_431_p1() {
    tmp_63_cast_fu_431_p1 = esl_sext<64,9>(tmp_53_fu_425_p2.read());
}

void max_pool_1chan::thread_tmp_fu_181_p2() {
    tmp_fu_181_p2 = (!i_reg_120.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): (sc_biguint<5>(i_reg_120.read()) < sc_biguint<5>(ap_const_lv5_1C));
}

void max_pool_1chan::thread_x_1_fu_448_p2() {
    x_1_fu_448_p2 = (!ap_const_lv32_1.is_01() || !x_fu_62.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(x_fu_62.read()));
}

void max_pool_1chan::thread_y_1_fu_436_p2() {
    y_1_fu_436_p2 = (!ap_const_lv32_1.is_01() || !y_fu_58.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(y_fu_58.read()));
}

void max_pool_1chan::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(tmp_fu_181_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(tmp_29_fu_253_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

