// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "resample_for_conv2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic resample_for_conv2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic resample_for_conv2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> resample_for_conv2::ap_ST_fsm_state1 = "1";
const sc_lv<2> resample_for_conv2::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<32> resample_for_conv2::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool resample_for_conv2::ap_const_boolean_1 = true;
const sc_lv<1> resample_for_conv2::ap_const_lv1_1 = "1";
const bool resample_for_conv2::ap_const_boolean_0 = false;
const sc_lv<32> resample_for_conv2::ap_const_lv32_1 = "1";
const sc_lv<1> resample_for_conv2::ap_const_lv1_0 = "0";
const sc_lv<2> resample_for_conv2::ap_const_lv2_0 = "00";
const sc_lv<4> resample_for_conv2::ap_const_lv4_0 = "0000";
const sc_lv<8> resample_for_conv2::ap_const_lv8_0 = "00000000";
const sc_lv<11> resample_for_conv2::ap_const_lv11_0 = "00000000000";
const sc_lv<4> resample_for_conv2::ap_const_lv4_1 = "1";
const sc_lv<2> resample_for_conv2::ap_const_lv2_1 = "1";
const sc_lv<11> resample_for_conv2::ap_const_lv11_1 = "1";
const sc_lv<8> resample_for_conv2::ap_const_lv8_1 = "1";
const sc_lv<2> resample_for_conv2::ap_const_lv2_3 = "11";
const sc_lv<4> resample_for_conv2::ap_const_lv4_9 = "1001";
const sc_lv<8> resample_for_conv2::ap_const_lv8_7E = "1111110";
const sc_lv<11> resample_for_conv2::ap_const_lv11_6E3 = "11011100011";
const sc_lv<4> resample_for_conv2::ap_const_lv4_3 = "11";
const sc_lv<32> resample_for_conv2::ap_const_lv32_2 = "10";
const sc_lv<32> resample_for_conv2::ap_const_lv32_3 = "11";
const sc_lv<4> resample_for_conv2::ap_const_lv4_5 = "101";
const sc_lv<8> resample_for_conv2::ap_const_lv8_E = "1110";
const sc_lv<11> resample_for_conv2::ap_const_lv11_C4 = "11000100";

resample_for_conv2::resample_for_conv2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    CNN_urem_4ns_4ns_eOg_U140 = new CNN_urem_4ns_4ns_eOg<1,8,4,4,4>("CNN_urem_4ns_4ns_eOg_U140");
    CNN_urem_4ns_4ns_eOg_U140->clk(ap_clk);
    CNN_urem_4ns_4ns_eOg_U140->reset(ap_rst);
    CNN_urem_4ns_4ns_eOg_U140->din0(k_1_mid2_fu_571_p3);
    CNN_urem_4ns_4ns_eOg_U140->din1(ap_var_for_const0);
    CNN_urem_4ns_4ns_eOg_U140->ce(grp_fu_631_ce);
    CNN_urem_4ns_4ns_eOg_U140->dout(grp_fu_631_p2);
    CNN_mux_432_25_1_1_U141 = new CNN_mux_432_25_1_1<1,1,25,25,25,25,32,25>("CNN_mux_432_25_1_1_U141");
    CNN_mux_432_25_1_1_U141->din0(square_image_0_V_q0);
    CNN_mux_432_25_1_1_U141->din1(square_image_1_V_q0);
    CNN_mux_432_25_1_1_U141->din2(square_image_2_V_q0);
    CNN_mux_432_25_1_1_U141->din3(square_image_3_V_q0);
    CNN_mux_432_25_1_1_U141->din4(tmp_12_fu_652_p5);
    CNN_mux_432_25_1_1_U141->dout(tmp_12_fu_652_p6);
    CNN_mac_muladd_9nfYi_U142 = new CNN_mac_muladd_9nfYi<1,2,9,4,8,11>("CNN_mac_muladd_9nfYi_U142");
    CNN_mac_muladd_9nfYi_U142->clk(ap_clk);
    CNN_mac_muladd_9nfYi_U142->reset(ap_rst);
    CNN_mac_muladd_9nfYi_U142->din0(grp_fu_715_p0);
    CNN_mac_muladd_9nfYi_U142->din1(grp_fu_715_p1);
    CNN_mac_muladd_9nfYi_U142->din2(grp_fu_715_p2);
    CNN_mac_muladd_9nfYi_U142->ce(grp_fu_715_ce);
    CNN_mac_muladd_9nfYi_U142->dout(grp_fu_715_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_275);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond_flatten2_reg_804_pp0_iter9_reg );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( rewind_enable );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_ap_idle_pp0_0to9);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_ap_phi_mux_exitcond_flatten3_phi_fu_170_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( exitcond_flatten3_reg_166 );
    sensitive << ( exitcond_flatten1_reg_799 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_exitcond_flatten4_phi_fu_185_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( exitcond_flatten4_reg_181 );
    sensitive << ( exitcond_flatten_reg_794 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_i_phi_fu_283_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( i_reg_279 );
    sensitive << ( i_mid2_reg_728 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten1_phi_fu_269_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( indvar_flatten1_reg_265 );
    sensitive << ( indvar_flatten_next1_reg_784 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten2_phi_fu_297_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( indvar_flatten2_reg_293 );
    sensitive << ( indvar_flatten_next2_reg_769 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_241_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( indvar_flatten_reg_237 );
    sensitive << ( indvar_flatten_next_reg_779 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_j_phi_fu_255_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( j_reg_251 );
    sensitive << ( j_mid2_reg_746 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_k_phi_fu_325_p6);
    sensitive << ( exitcond_flatten2_reg_804_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( k_reg_321 );
    sensitive << ( k_mid2_reg_813 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_k_s_phi_fu_311_p6);
    sensitive << ( exitcond_flatten2_reg_804_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( k_s_reg_307 );
    sensitive << ( tmp_10_reg_847 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_l_phi_fu_353_p6);
    sensitive << ( l_reg_349 );
    sensitive << ( exitcond_flatten2_reg_804_pp0_iter8_reg );
    sensitive << ( l_mid2_reg_858 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_l_s_phi_fu_339_p6);
    sensitive << ( l_s_reg_335 );
    sensitive << ( exitcond_flatten2_reg_804_pp0_iter8_reg );
    sensitive << ( l_1_mid2_reg_863 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_m_cast_phi_fu_213_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( m_cast_reg_209 );
    sensitive << ( m_cast_mid2_reg_757 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_n_phi_fu_227_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( n_reg_223 );
    sensitive << ( n_1_reg_774 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_phi_mux_tmp_1_phi_fu_199_p6);
    sensitive << ( exitcond_flatten2_reg_804 );
    sensitive << ( tmp_1_reg_195 );
    sensitive << ( tmp_3_reg_789 );
    sensitive << ( ap_condition_275 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to9 );

    SC_METHOD(thread_exitcond_flatten1_fu_539_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( indvar_flatten_next1_fu_519_p3 );

    SC_METHOD(thread_exitcond_flatten2_fu_545_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten2_phi_fu_297_p6 );

    SC_METHOD(thread_exitcond_flatten_fu_533_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( indvar_flatten_next_fu_505_p3 );

    SC_METHOD(thread_exitcond_flatten_mid_fu_389_p2);
    sensitive << ( ap_phi_mux_exitcond_flatten4_phi_fu_185_p6 );
    sensitive << ( not_exitcond_flatten_fu_377_p2 );

    SC_METHOD(thread_exitcond_flatten_not_fu_423_p2);
    sensitive << ( ap_phi_mux_exitcond_flatten4_phi_fu_185_p6 );

    SC_METHOD(thread_grp_fu_631_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );

    SC_METHOD(thread_grp_fu_715_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );

    SC_METHOD(thread_grp_fu_715_p0);
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_715_p1);
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_fu_715_p10 );

    SC_METHOD(thread_grp_fu_715_p10);
    sensitive << ( grp_fu_631_p2 );

    SC_METHOD(thread_grp_fu_715_p2);
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_fu_715_p20 );

    SC_METHOD(thread_grp_fu_715_p20);
    sensitive << ( l_1_mid2_reg_863 );

    SC_METHOD(thread_i_1_fu_363_p2);
    sensitive << ( ap_phi_mux_i_phi_fu_283_p6 );

    SC_METHOD(thread_i_mid2_fu_395_p3);
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );
    sensitive << ( ap_phi_mux_i_phi_fu_283_p6 );
    sensitive << ( i_1_fu_363_p2 );

    SC_METHOD(thread_indvar_flatten17_op_fu_513_p2);
    sensitive << ( ap_phi_mux_indvar_flatten1_phi_fu_269_p6 );

    SC_METHOD(thread_indvar_flatten_next1_fu_519_p3);
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );
    sensitive << ( indvar_flatten17_op_fu_513_p2 );

    SC_METHOD(thread_indvar_flatten_next2_fu_487_p2);
    sensitive << ( ap_phi_mux_indvar_flatten2_phi_fu_297_p6 );

    SC_METHOD(thread_indvar_flatten_next_fu_505_p3);
    sensitive << ( tmp_fu_409_p2 );
    sensitive << ( indvar_flatten_op_fu_499_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_499_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_241_p6 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( exitcond_flatten2_reg_804_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_j_1_fu_403_p2);
    sensitive << ( j_mid_fu_369_p3 );

    SC_METHOD(thread_j_mid2_fu_441_p3);
    sensitive << ( exitcond_flatten_mid_fu_389_p2 );
    sensitive << ( j_mid_fu_369_p3 );
    sensitive << ( j_1_fu_403_p2 );

    SC_METHOD(thread_j_mid_fu_369_p3);
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );
    sensitive << ( ap_phi_mux_j_phi_fu_255_p6 );

    SC_METHOD(thread_k_1_mid2_fu_571_p3);
    sensitive << ( tmp_3_mid1_reg_740 );
    sensitive << ( k_2_dup_fu_565_p2 );
    sensitive << ( k_1_mid_fu_558_p3 );

    SC_METHOD(thread_k_1_mid_fu_558_p3);
    sensitive << ( tmp_reg_734 );
    sensitive << ( ap_phi_mux_k_s_phi_fu_311_p6 );

    SC_METHOD(thread_k_2_dup_fu_565_p2);
    sensitive << ( k_mid_fu_551_p3 );

    SC_METHOD(thread_k_mid2_fu_581_p3);
    sensitive << ( tmp_3_mid1_reg_740 );
    sensitive << ( k_mid_fu_551_p3 );
    sensitive << ( k_2_dup_fu_565_p2 );

    SC_METHOD(thread_k_mid_fu_551_p3);
    sensitive << ( tmp_reg_734 );
    sensitive << ( ap_phi_mux_k_phi_fu_325_p6 );

    SC_METHOD(thread_l_1_mid2_fu_694_p3);
    sensitive << ( exitcond_flatten_mid_reg_723_pp0_iter7_reg );
    sensitive << ( l_1_mid_fu_672_p3 );
    sensitive << ( tmp_2_fu_688_p2 );

    SC_METHOD(thread_l_1_mid_fu_672_p3);
    sensitive << ( exitcond_flatten3_reg_166_pp0_iter7_reg );
    sensitive << ( ap_phi_mux_l_s_phi_fu_339_p6 );
    sensitive << ( l_2_dup_fu_666_p2 );

    SC_METHOD(thread_l_2_dup_fu_666_p2);
    sensitive << ( ap_phi_mux_l_phi_fu_353_p6 );

    SC_METHOD(thread_l_mid2_fu_680_p3);
    sensitive << ( exitcond_flatten3_reg_166_pp0_iter7_reg );
    sensitive << ( ap_phi_mux_l_phi_fu_353_p6 );
    sensitive << ( l_2_dup_fu_666_p2 );

    SC_METHOD(thread_m_cast_mid2_cast_fu_578_p1);
    sensitive << ( m_cast_mid2_reg_757 );

    SC_METHOD(thread_m_cast_mid2_fu_475_p3);
    sensitive << ( tmp_3_mid1_fu_435_p2 );
    sensitive << ( m_mid_fu_415_p3 );
    sensitive << ( m_fu_449_p2 );

    SC_METHOD(thread_m_fu_449_p2);
    sensitive << ( m_mid_fu_415_p3 );

    SC_METHOD(thread_m_mid_fu_415_p3);
    sensitive << ( tmp_fu_409_p2 );
    sensitive << ( ap_phi_mux_m_cast_phi_fu_213_p6 );

    SC_METHOD(thread_n_1_fu_493_p2);
    sensitive << ( n_mid2_fu_467_p3 );

    SC_METHOD(thread_n_cast_fu_588_p1);
    sensitive << ( n_mid2_reg_752 );

    SC_METHOD(thread_n_mid2_fu_467_p3);
    sensitive << ( ap_phi_mux_n_phi_fu_227_p6 );
    sensitive << ( tmp_5_fu_461_p2 );

    SC_METHOD(thread_newIndex_trunc_fu_611_p2);
    sensitive << ( m_cast_mid2_reg_757 );
    sensitive << ( tmp_7_reg_764 );

    SC_METHOD(thread_not_exitcond_flatten_1_fu_429_p2);
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );
    sensitive << ( exitcond_flatten_not_fu_423_p2 );

    SC_METHOD(thread_not_exitcond_flatten_fu_377_p2);
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );

    SC_METHOD(thread_resampled_0_V_address0);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_17_cast_fu_708_p1 );

    SC_METHOD(thread_resampled_0_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_resampled_0_V_d0);
    sensitive << ( tmp_12_reg_852_pp0_iter9_reg );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_resampled_0_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_15_reg_843_pp0_iter9_reg );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_resampled_1_V_address0);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_17_cast_fu_708_p1 );

    SC_METHOD(thread_resampled_1_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_resampled_1_V_d0);
    sensitive << ( tmp_12_reg_852_pp0_iter9_reg );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_resampled_1_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_15_reg_843_pp0_iter9_reg );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_rewind_ap_ready);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond_flatten2_fu_545_p2 );
    sensitive << ( rewind_ap_ready_reg );

    SC_METHOD(thread_rewind_enable);
    sensitive << ( ap_start );
    sensitive << ( rewind_ap_ready_reg );

    SC_METHOD(thread_square_image_0_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_11_fu_623_p1 );

    SC_METHOD(thread_square_image_0_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_square_image_1_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_11_fu_623_p1 );

    SC_METHOD(thread_square_image_1_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_square_image_2_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_11_fu_623_p1 );

    SC_METHOD(thread_square_image_2_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_square_image_3_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_11_fu_623_p1 );

    SC_METHOD(thread_square_image_3_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_tmp_10_fu_643_p2);
    sensitive << ( k_1_mid2_fu_571_p3 );

    SC_METHOD(thread_tmp_11_fu_623_p1);
    sensitive << ( tmp_9_fu_615_p3 );

    SC_METHOD(thread_tmp_12_fu_652_p5);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( arrayNo_reg_818 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_15_fu_637_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( k_1_mid2_fu_571_p3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_tmp_17_cast_fu_708_p1);
    sensitive << ( tmp_14_reg_874 );

    SC_METHOD(thread_tmp_2_fu_688_p2);
    sensitive << ( l_1_mid_fu_672_p3 );

    SC_METHOD(thread_tmp_3_fu_527_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( n_1_fu_493_p2 );

    SC_METHOD(thread_tmp_3_mid1_fu_435_p2);
    sensitive << ( tmp_3_mid_fu_383_p2 );
    sensitive << ( not_exitcond_flatten_1_fu_429_p2 );

    SC_METHOD(thread_tmp_3_mid_fu_383_p2);
    sensitive << ( ap_phi_mux_tmp_1_phi_fu_199_p6 );
    sensitive << ( not_exitcond_flatten_fu_377_p2 );

    SC_METHOD(thread_tmp_4_fu_455_p2);
    sensitive << ( exitcond_flatten_mid_fu_389_p2 );
    sensitive << ( tmp_3_mid1_fu_435_p2 );

    SC_METHOD(thread_tmp_5_fu_461_p2);
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );
    sensitive << ( tmp_4_fu_455_p2 );

    SC_METHOD(thread_tmp_6_fu_591_p2);
    sensitive << ( j_mid2_reg_746 );
    sensitive << ( n_cast_fu_588_p1 );

    SC_METHOD(thread_tmp_7_fu_483_p1);
    sensitive << ( i_mid2_fu_395_p3 );

    SC_METHOD(thread_tmp_8_fu_596_p2);
    sensitive << ( i_mid2_reg_728 );
    sensitive << ( m_cast_mid2_cast_fu_578_p1 );

    SC_METHOD(thread_tmp_9_fu_615_p3);
    sensitive << ( newIndex_trunc_fu_611_p2 );
    sensitive << ( tmp_6_fu_591_p2 );

    SC_METHOD(thread_tmp_fu_409_p2);
    sensitive << ( exitcond_flatten_mid_fu_389_p2 );
    sensitive << ( ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    rewind_ap_ready_reg = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "resample_for_conv2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, square_image_0_V_address0, "(port)square_image_0_V_address0");
    sc_trace(mVcdFile, square_image_0_V_ce0, "(port)square_image_0_V_ce0");
    sc_trace(mVcdFile, square_image_0_V_q0, "(port)square_image_0_V_q0");
    sc_trace(mVcdFile, square_image_1_V_address0, "(port)square_image_1_V_address0");
    sc_trace(mVcdFile, square_image_1_V_ce0, "(port)square_image_1_V_ce0");
    sc_trace(mVcdFile, square_image_1_V_q0, "(port)square_image_1_V_q0");
    sc_trace(mVcdFile, square_image_2_V_address0, "(port)square_image_2_V_address0");
    sc_trace(mVcdFile, square_image_2_V_ce0, "(port)square_image_2_V_ce0");
    sc_trace(mVcdFile, square_image_2_V_q0, "(port)square_image_2_V_q0");
    sc_trace(mVcdFile, square_image_3_V_address0, "(port)square_image_3_V_address0");
    sc_trace(mVcdFile, square_image_3_V_ce0, "(port)square_image_3_V_ce0");
    sc_trace(mVcdFile, square_image_3_V_q0, "(port)square_image_3_V_q0");
    sc_trace(mVcdFile, resampled_0_V_address0, "(port)resampled_0_V_address0");
    sc_trace(mVcdFile, resampled_0_V_ce0, "(port)resampled_0_V_ce0");
    sc_trace(mVcdFile, resampled_0_V_we0, "(port)resampled_0_V_we0");
    sc_trace(mVcdFile, resampled_0_V_d0, "(port)resampled_0_V_d0");
    sc_trace(mVcdFile, resampled_1_V_address0, "(port)resampled_1_V_address0");
    sc_trace(mVcdFile, resampled_1_V_ce0, "(port)resampled_1_V_ce0");
    sc_trace(mVcdFile, resampled_1_V_we0, "(port)resampled_1_V_we0");
    sc_trace(mVcdFile, resampled_1_V_d0, "(port)resampled_1_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804, "exitcond_flatten2_reg_804");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter1_reg, "exitcond_flatten2_reg_804_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166, "exitcond_flatten3_reg_166");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter1_reg, "exitcond_flatten3_reg_166_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter2_reg, "exitcond_flatten3_reg_166_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter3_reg, "exitcond_flatten3_reg_166_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter4_reg, "exitcond_flatten3_reg_166_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter5_reg, "exitcond_flatten3_reg_166_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter6_reg, "exitcond_flatten3_reg_166_pp0_iter6_reg");
    sc_trace(mVcdFile, exitcond_flatten3_reg_166_pp0_iter7_reg, "exitcond_flatten3_reg_166_pp0_iter7_reg");
    sc_trace(mVcdFile, exitcond_flatten4_reg_181, "exitcond_flatten4_reg_181");
    sc_trace(mVcdFile, tmp_1_reg_195, "tmp_1_reg_195");
    sc_trace(mVcdFile, m_cast_reg_209, "m_cast_reg_209");
    sc_trace(mVcdFile, n_reg_223, "n_reg_223");
    sc_trace(mVcdFile, indvar_flatten_reg_237, "indvar_flatten_reg_237");
    sc_trace(mVcdFile, j_reg_251, "j_reg_251");
    sc_trace(mVcdFile, indvar_flatten1_reg_265, "indvar_flatten1_reg_265");
    sc_trace(mVcdFile, i_reg_279, "i_reg_279");
    sc_trace(mVcdFile, indvar_flatten2_reg_293, "indvar_flatten2_reg_293");
    sc_trace(mVcdFile, k_s_reg_307, "k_s_reg_307");
    sc_trace(mVcdFile, k_reg_321, "k_reg_321");
    sc_trace(mVcdFile, l_s_reg_335, "l_s_reg_335");
    sc_trace(mVcdFile, l_reg_349, "l_reg_349");
    sc_trace(mVcdFile, exitcond_flatten_mid_fu_389_p2, "exitcond_flatten_mid_fu_389_p2");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723, "exitcond_flatten_mid_reg_723");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter1_reg, "exitcond_flatten_mid_reg_723_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter2_reg, "exitcond_flatten_mid_reg_723_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter3_reg, "exitcond_flatten_mid_reg_723_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter4_reg, "exitcond_flatten_mid_reg_723_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter5_reg, "exitcond_flatten_mid_reg_723_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter6_reg, "exitcond_flatten_mid_reg_723_pp0_iter6_reg");
    sc_trace(mVcdFile, exitcond_flatten_mid_reg_723_pp0_iter7_reg, "exitcond_flatten_mid_reg_723_pp0_iter7_reg");
    sc_trace(mVcdFile, i_mid2_fu_395_p3, "i_mid2_fu_395_p3");
    sc_trace(mVcdFile, i_mid2_reg_728, "i_mid2_reg_728");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_fu_409_p2, "tmp_fu_409_p2");
    sc_trace(mVcdFile, tmp_reg_734, "tmp_reg_734");
    sc_trace(mVcdFile, tmp_3_mid1_fu_435_p2, "tmp_3_mid1_fu_435_p2");
    sc_trace(mVcdFile, tmp_3_mid1_reg_740, "tmp_3_mid1_reg_740");
    sc_trace(mVcdFile, j_mid2_fu_441_p3, "j_mid2_fu_441_p3");
    sc_trace(mVcdFile, j_mid2_reg_746, "j_mid2_reg_746");
    sc_trace(mVcdFile, n_mid2_fu_467_p3, "n_mid2_fu_467_p3");
    sc_trace(mVcdFile, n_mid2_reg_752, "n_mid2_reg_752");
    sc_trace(mVcdFile, m_cast_mid2_fu_475_p3, "m_cast_mid2_fu_475_p3");
    sc_trace(mVcdFile, m_cast_mid2_reg_757, "m_cast_mid2_reg_757");
    sc_trace(mVcdFile, tmp_7_fu_483_p1, "tmp_7_fu_483_p1");
    sc_trace(mVcdFile, tmp_7_reg_764, "tmp_7_reg_764");
    sc_trace(mVcdFile, indvar_flatten_next2_fu_487_p2, "indvar_flatten_next2_fu_487_p2");
    sc_trace(mVcdFile, indvar_flatten_next2_reg_769, "indvar_flatten_next2_reg_769");
    sc_trace(mVcdFile, n_1_fu_493_p2, "n_1_fu_493_p2");
    sc_trace(mVcdFile, n_1_reg_774, "n_1_reg_774");
    sc_trace(mVcdFile, indvar_flatten_next_fu_505_p3, "indvar_flatten_next_fu_505_p3");
    sc_trace(mVcdFile, indvar_flatten_next_reg_779, "indvar_flatten_next_reg_779");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_519_p3, "indvar_flatten_next1_fu_519_p3");
    sc_trace(mVcdFile, indvar_flatten_next1_reg_784, "indvar_flatten_next1_reg_784");
    sc_trace(mVcdFile, tmp_3_fu_527_p2, "tmp_3_fu_527_p2");
    sc_trace(mVcdFile, tmp_3_reg_789, "tmp_3_reg_789");
    sc_trace(mVcdFile, exitcond_flatten_fu_533_p2, "exitcond_flatten_fu_533_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_794, "exitcond_flatten_reg_794");
    sc_trace(mVcdFile, exitcond_flatten1_fu_539_p2, "exitcond_flatten1_fu_539_p2");
    sc_trace(mVcdFile, exitcond_flatten1_reg_799, "exitcond_flatten1_reg_799");
    sc_trace(mVcdFile, exitcond_flatten2_fu_545_p2, "exitcond_flatten2_fu_545_p2");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter2_reg, "exitcond_flatten2_reg_804_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter3_reg, "exitcond_flatten2_reg_804_pp0_iter3_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter4_reg, "exitcond_flatten2_reg_804_pp0_iter4_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter5_reg, "exitcond_flatten2_reg_804_pp0_iter5_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter6_reg, "exitcond_flatten2_reg_804_pp0_iter6_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter7_reg, "exitcond_flatten2_reg_804_pp0_iter7_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter8_reg, "exitcond_flatten2_reg_804_pp0_iter8_reg");
    sc_trace(mVcdFile, exitcond_flatten2_reg_804_pp0_iter9_reg, "exitcond_flatten2_reg_804_pp0_iter9_reg");
    sc_trace(mVcdFile, k_1_mid2_fu_571_p3, "k_1_mid2_fu_571_p3");
    sc_trace(mVcdFile, k_mid2_fu_581_p3, "k_mid2_fu_581_p3");
    sc_trace(mVcdFile, k_mid2_reg_813, "k_mid2_reg_813");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, arrayNo_reg_818, "arrayNo_reg_818");
    sc_trace(mVcdFile, tmp_15_fu_637_p2, "tmp_15_fu_637_p2");
    sc_trace(mVcdFile, tmp_15_reg_843, "tmp_15_reg_843");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter2_reg, "tmp_15_reg_843_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter3_reg, "tmp_15_reg_843_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter4_reg, "tmp_15_reg_843_pp0_iter4_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter5_reg, "tmp_15_reg_843_pp0_iter5_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter6_reg, "tmp_15_reg_843_pp0_iter6_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter7_reg, "tmp_15_reg_843_pp0_iter7_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter8_reg, "tmp_15_reg_843_pp0_iter8_reg");
    sc_trace(mVcdFile, tmp_15_reg_843_pp0_iter9_reg, "tmp_15_reg_843_pp0_iter9_reg");
    sc_trace(mVcdFile, tmp_10_fu_643_p2, "tmp_10_fu_643_p2");
    sc_trace(mVcdFile, tmp_10_reg_847, "tmp_10_reg_847");
    sc_trace(mVcdFile, tmp_12_fu_652_p6, "tmp_12_fu_652_p6");
    sc_trace(mVcdFile, tmp_12_reg_852, "tmp_12_reg_852");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter3_reg, "tmp_12_reg_852_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter4_reg, "tmp_12_reg_852_pp0_iter4_reg");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter5_reg, "tmp_12_reg_852_pp0_iter5_reg");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter6_reg, "tmp_12_reg_852_pp0_iter6_reg");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter7_reg, "tmp_12_reg_852_pp0_iter7_reg");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter8_reg, "tmp_12_reg_852_pp0_iter8_reg");
    sc_trace(mVcdFile, tmp_12_reg_852_pp0_iter9_reg, "tmp_12_reg_852_pp0_iter9_reg");
    sc_trace(mVcdFile, l_mid2_fu_680_p3, "l_mid2_fu_680_p3");
    sc_trace(mVcdFile, l_mid2_reg_858, "l_mid2_reg_858");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, l_1_mid2_fu_694_p3, "l_1_mid2_fu_694_p3");
    sc_trace(mVcdFile, l_1_mid2_reg_863, "l_1_mid2_reg_863");
    sc_trace(mVcdFile, grp_fu_715_p3, "grp_fu_715_p3");
    sc_trace(mVcdFile, tmp_14_reg_874, "tmp_14_reg_874");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, rewind_ap_ready, "rewind_ap_ready");
    sc_trace(mVcdFile, rewind_ap_ready_reg, "rewind_ap_ready_reg");
    sc_trace(mVcdFile, rewind_enable, "rewind_enable");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_phi_mux_exitcond_flatten3_phi_fu_170_p6, "ap_phi_mux_exitcond_flatten3_phi_fu_170_p6");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_exitcond_flatten4_phi_fu_185_p6, "ap_phi_mux_exitcond_flatten4_phi_fu_185_p6");
    sc_trace(mVcdFile, ap_phi_mux_tmp_1_phi_fu_199_p6, "ap_phi_mux_tmp_1_phi_fu_199_p6");
    sc_trace(mVcdFile, ap_phi_mux_m_cast_phi_fu_213_p6, "ap_phi_mux_m_cast_phi_fu_213_p6");
    sc_trace(mVcdFile, ap_phi_mux_n_phi_fu_227_p6, "ap_phi_mux_n_phi_fu_227_p6");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_241_p6, "ap_phi_mux_indvar_flatten_phi_fu_241_p6");
    sc_trace(mVcdFile, ap_phi_mux_j_phi_fu_255_p6, "ap_phi_mux_j_phi_fu_255_p6");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten1_phi_fu_269_p6, "ap_phi_mux_indvar_flatten1_phi_fu_269_p6");
    sc_trace(mVcdFile, ap_phi_mux_i_phi_fu_283_p6, "ap_phi_mux_i_phi_fu_283_p6");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten2_phi_fu_297_p6, "ap_phi_mux_indvar_flatten2_phi_fu_297_p6");
    sc_trace(mVcdFile, ap_phi_mux_k_s_phi_fu_311_p6, "ap_phi_mux_k_s_phi_fu_311_p6");
    sc_trace(mVcdFile, ap_phi_mux_k_phi_fu_325_p6, "ap_phi_mux_k_phi_fu_325_p6");
    sc_trace(mVcdFile, ap_phi_mux_l_s_phi_fu_339_p6, "ap_phi_mux_l_s_phi_fu_339_p6");
    sc_trace(mVcdFile, ap_phi_mux_l_phi_fu_353_p6, "ap_phi_mux_l_phi_fu_353_p6");
    sc_trace(mVcdFile, tmp_11_fu_623_p1, "tmp_11_fu_623_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_708_p1, "tmp_17_cast_fu_708_p1");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_377_p2, "not_exitcond_flatten_fu_377_p2");
    sc_trace(mVcdFile, i_1_fu_363_p2, "i_1_fu_363_p2");
    sc_trace(mVcdFile, j_mid_fu_369_p3, "j_mid_fu_369_p3");
    sc_trace(mVcdFile, exitcond_flatten_not_fu_423_p2, "exitcond_flatten_not_fu_423_p2");
    sc_trace(mVcdFile, tmp_3_mid_fu_383_p2, "tmp_3_mid_fu_383_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_1_fu_429_p2, "not_exitcond_flatten_1_fu_429_p2");
    sc_trace(mVcdFile, j_1_fu_403_p2, "j_1_fu_403_p2");
    sc_trace(mVcdFile, m_mid_fu_415_p3, "m_mid_fu_415_p3");
    sc_trace(mVcdFile, tmp_4_fu_455_p2, "tmp_4_fu_455_p2");
    sc_trace(mVcdFile, tmp_5_fu_461_p2, "tmp_5_fu_461_p2");
    sc_trace(mVcdFile, m_fu_449_p2, "m_fu_449_p2");
    sc_trace(mVcdFile, indvar_flatten_op_fu_499_p2, "indvar_flatten_op_fu_499_p2");
    sc_trace(mVcdFile, indvar_flatten17_op_fu_513_p2, "indvar_flatten17_op_fu_513_p2");
    sc_trace(mVcdFile, k_mid_fu_551_p3, "k_mid_fu_551_p3");
    sc_trace(mVcdFile, k_2_dup_fu_565_p2, "k_2_dup_fu_565_p2");
    sc_trace(mVcdFile, k_1_mid_fu_558_p3, "k_1_mid_fu_558_p3");
    sc_trace(mVcdFile, n_cast_fu_588_p1, "n_cast_fu_588_p1");
    sc_trace(mVcdFile, m_cast_mid2_cast_fu_578_p1, "m_cast_mid2_cast_fu_578_p1");
    sc_trace(mVcdFile, tmp_8_fu_596_p2, "tmp_8_fu_596_p2");
    sc_trace(mVcdFile, newIndex_trunc_fu_611_p2, "newIndex_trunc_fu_611_p2");
    sc_trace(mVcdFile, tmp_6_fu_591_p2, "tmp_6_fu_591_p2");
    sc_trace(mVcdFile, tmp_9_fu_615_p3, "tmp_9_fu_615_p3");
    sc_trace(mVcdFile, tmp_12_fu_652_p5, "tmp_12_fu_652_p5");
    sc_trace(mVcdFile, l_2_dup_fu_666_p2, "l_2_dup_fu_666_p2");
    sc_trace(mVcdFile, l_1_mid_fu_672_p3, "l_1_mid_fu_672_p3");
    sc_trace(mVcdFile, tmp_2_fu_688_p2, "tmp_2_fu_688_p2");
    sc_trace(mVcdFile, grp_fu_631_p2, "grp_fu_631_p2");
    sc_trace(mVcdFile, grp_fu_715_p0, "grp_fu_715_p0");
    sc_trace(mVcdFile, grp_fu_715_p1, "grp_fu_715_p1");
    sc_trace(mVcdFile, grp_fu_715_p2, "grp_fu_715_p2");
    sc_trace(mVcdFile, grp_fu_631_ce, "grp_fu_631_ce");
    sc_trace(mVcdFile, grp_fu_715_ce, "grp_fu_715_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to9, "ap_idle_pp0_0to9");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_715_p10, "grp_fu_715_p10");
    sc_trace(mVcdFile, grp_fu_715_p20, "grp_fu_715_p20");
    sc_trace(mVcdFile, ap_condition_275, "ap_condition_275");
#endif

    }
}

resample_for_conv2::~resample_for_conv2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete CNN_urem_4ns_4ns_eOg_U140;
    delete CNN_mux_432_25_1_1_U141;
    delete CNN_mac_muladd_9nfYi_U142;
}

void resample_for_conv2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv4_5;
}

void resample_for_conv2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_reg_804_pp0_iter9_reg.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter1 = rewind_enable.read();
        } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter10 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        exitcond_flatten3_reg_166 = exitcond_flatten1_reg_799.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        exitcond_flatten3_reg_166 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        exitcond_flatten4_reg_181 = exitcond_flatten_reg_794.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        exitcond_flatten4_reg_181 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        i_reg_279 = i_mid2_reg_728.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        i_reg_279 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        indvar_flatten1_reg_265 = indvar_flatten_next1_reg_784.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        indvar_flatten1_reg_265 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        indvar_flatten2_reg_293 = indvar_flatten_next2_reg_769.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        indvar_flatten2_reg_293 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_237 = indvar_flatten_next_reg_779.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        indvar_flatten_reg_237 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        j_reg_251 = j_mid2_reg_746.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        j_reg_251 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        k_reg_321 = k_mid2_reg_813.read();
    } else if (((esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
                (!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())))) {
        k_reg_321 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        k_s_reg_307 = tmp_10_reg_847.read();
    } else if (((esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_1) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
                (!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())))) {
        k_s_reg_307 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter8_reg.read(), ap_const_lv1_0))) {
        l_reg_349 = l_mid2_reg_858.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_reg_804_pp0_iter8_reg.read())))) {
        l_reg_349 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter8_reg.read(), ap_const_lv1_0))) {
        l_s_reg_335 = l_1_mid2_reg_863.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_reg_804_pp0_iter8_reg.read())))) {
        l_s_reg_335 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        m_cast_reg_209 = m_cast_mid2_reg_757.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        m_cast_reg_209 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        n_reg_223 = n_1_reg_774.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        n_reg_223 = ap_const_lv2_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        rewind_ap_ready_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()))) {
            rewind_ap_ready_reg = rewind_ap_ready.read();
        } else {
            rewind_ap_ready_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0))) {
        tmp_1_reg_195 = tmp_3_reg_789.read();
    } else if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)))) {
        tmp_1_reg_195 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
        arrayNo_reg_818 = tmp_8_fu_596_p2.read().range(3, 2);
        exitcond_flatten2_reg_804 = exitcond_flatten2_fu_545_p2.read();
        exitcond_flatten2_reg_804_pp0_iter1_reg = exitcond_flatten2_reg_804.read();
        exitcond_flatten3_reg_166_pp0_iter1_reg = exitcond_flatten3_reg_166.read();
        exitcond_flatten_mid_reg_723 = exitcond_flatten_mid_fu_389_p2.read();
        exitcond_flatten_mid_reg_723_pp0_iter1_reg = exitcond_flatten_mid_reg_723.read();
        n_mid2_reg_752 = n_mid2_fu_467_p3.read();
        tmp_15_reg_843 = tmp_15_fu_637_p2.read();
        tmp_3_mid1_reg_740 = tmp_3_mid1_fu_435_p2.read();
        tmp_7_reg_764 = tmp_7_fu_483_p1.read();
        tmp_reg_734 = tmp_fu_409_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        exitcond_flatten1_reg_799 = exitcond_flatten1_fu_539_p2.read();
        exitcond_flatten_reg_794 = exitcond_flatten_fu_533_p2.read();
        i_mid2_reg_728 = i_mid2_fu_395_p3.read();
        indvar_flatten_next1_reg_784 = indvar_flatten_next1_fu_519_p3.read();
        indvar_flatten_next2_reg_769 = indvar_flatten_next2_fu_487_p2.read();
        indvar_flatten_next_reg_779 = indvar_flatten_next_fu_505_p3.read();
        j_mid2_reg_746 = j_mid2_fu_441_p3.read();
        m_cast_mid2_reg_757 = m_cast_mid2_fu_475_p3.read();
        n_1_reg_774 = n_1_fu_493_p2.read();
        tmp_3_reg_789 = tmp_3_fu_527_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond_flatten2_reg_804_pp0_iter2_reg = exitcond_flatten2_reg_804_pp0_iter1_reg.read();
        exitcond_flatten2_reg_804_pp0_iter3_reg = exitcond_flatten2_reg_804_pp0_iter2_reg.read();
        exitcond_flatten2_reg_804_pp0_iter4_reg = exitcond_flatten2_reg_804_pp0_iter3_reg.read();
        exitcond_flatten2_reg_804_pp0_iter5_reg = exitcond_flatten2_reg_804_pp0_iter4_reg.read();
        exitcond_flatten2_reg_804_pp0_iter6_reg = exitcond_flatten2_reg_804_pp0_iter5_reg.read();
        exitcond_flatten2_reg_804_pp0_iter7_reg = exitcond_flatten2_reg_804_pp0_iter6_reg.read();
        exitcond_flatten2_reg_804_pp0_iter8_reg = exitcond_flatten2_reg_804_pp0_iter7_reg.read();
        exitcond_flatten2_reg_804_pp0_iter9_reg = exitcond_flatten2_reg_804_pp0_iter8_reg.read();
        exitcond_flatten3_reg_166_pp0_iter2_reg = exitcond_flatten3_reg_166_pp0_iter1_reg.read();
        exitcond_flatten3_reg_166_pp0_iter3_reg = exitcond_flatten3_reg_166_pp0_iter2_reg.read();
        exitcond_flatten3_reg_166_pp0_iter4_reg = exitcond_flatten3_reg_166_pp0_iter3_reg.read();
        exitcond_flatten3_reg_166_pp0_iter5_reg = exitcond_flatten3_reg_166_pp0_iter4_reg.read();
        exitcond_flatten3_reg_166_pp0_iter6_reg = exitcond_flatten3_reg_166_pp0_iter5_reg.read();
        exitcond_flatten3_reg_166_pp0_iter7_reg = exitcond_flatten3_reg_166_pp0_iter6_reg.read();
        exitcond_flatten_mid_reg_723_pp0_iter2_reg = exitcond_flatten_mid_reg_723_pp0_iter1_reg.read();
        exitcond_flatten_mid_reg_723_pp0_iter3_reg = exitcond_flatten_mid_reg_723_pp0_iter2_reg.read();
        exitcond_flatten_mid_reg_723_pp0_iter4_reg = exitcond_flatten_mid_reg_723_pp0_iter3_reg.read();
        exitcond_flatten_mid_reg_723_pp0_iter5_reg = exitcond_flatten_mid_reg_723_pp0_iter4_reg.read();
        exitcond_flatten_mid_reg_723_pp0_iter6_reg = exitcond_flatten_mid_reg_723_pp0_iter5_reg.read();
        exitcond_flatten_mid_reg_723_pp0_iter7_reg = exitcond_flatten_mid_reg_723_pp0_iter6_reg.read();
        tmp_12_reg_852 = tmp_12_fu_652_p6.read();
        tmp_12_reg_852_pp0_iter3_reg = tmp_12_reg_852.read();
        tmp_12_reg_852_pp0_iter4_reg = tmp_12_reg_852_pp0_iter3_reg.read();
        tmp_12_reg_852_pp0_iter5_reg = tmp_12_reg_852_pp0_iter4_reg.read();
        tmp_12_reg_852_pp0_iter6_reg = tmp_12_reg_852_pp0_iter5_reg.read();
        tmp_12_reg_852_pp0_iter7_reg = tmp_12_reg_852_pp0_iter6_reg.read();
        tmp_12_reg_852_pp0_iter8_reg = tmp_12_reg_852_pp0_iter7_reg.read();
        tmp_12_reg_852_pp0_iter9_reg = tmp_12_reg_852_pp0_iter8_reg.read();
        tmp_15_reg_843_pp0_iter2_reg = tmp_15_reg_843.read();
        tmp_15_reg_843_pp0_iter3_reg = tmp_15_reg_843_pp0_iter2_reg.read();
        tmp_15_reg_843_pp0_iter4_reg = tmp_15_reg_843_pp0_iter3_reg.read();
        tmp_15_reg_843_pp0_iter5_reg = tmp_15_reg_843_pp0_iter4_reg.read();
        tmp_15_reg_843_pp0_iter6_reg = tmp_15_reg_843_pp0_iter5_reg.read();
        tmp_15_reg_843_pp0_iter7_reg = tmp_15_reg_843_pp0_iter6_reg.read();
        tmp_15_reg_843_pp0_iter8_reg = tmp_15_reg_843_pp0_iter7_reg.read();
        tmp_15_reg_843_pp0_iter9_reg = tmp_15_reg_843_pp0_iter8_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        k_mid2_reg_813 = k_mid2_fu_581_p3.read();
        tmp_10_reg_847 = tmp_10_fu_643_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()))) {
        l_1_mid2_reg_863 = l_1_mid2_fu_694_p3.read();
        l_mid2_reg_858 = l_mid2_fu_680_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        tmp_14_reg_874 = grp_fu_715_p3.read();
    }
}

void resample_for_conv2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void resample_for_conv2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void resample_for_conv2::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1);
}

void resample_for_conv2::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1);
}

void resample_for_conv2::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void resample_for_conv2::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void resample_for_conv2::thread_ap_condition_275() {
    ap_condition_275 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0));
}

void resample_for_conv2::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_reg_804_pp0_iter9_reg.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void resample_for_conv2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void resample_for_conv2::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = rewind_enable.read();
}

void resample_for_conv2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_ap_idle_pp0_0to9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()))) {
        ap_idle_pp0_0to9 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to9 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_ap_phi_mux_exitcond_flatten3_phi_fu_170_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 = exitcond_flatten1_reg_799.read();
        } else {
            ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 = exitcond_flatten3_reg_166.read();
        }
    } else {
        ap_phi_mux_exitcond_flatten3_phi_fu_170_p6 = exitcond_flatten3_reg_166.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_exitcond_flatten4_phi_fu_185_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_exitcond_flatten4_phi_fu_185_p6 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_exitcond_flatten4_phi_fu_185_p6 = exitcond_flatten_reg_794.read();
        } else {
            ap_phi_mux_exitcond_flatten4_phi_fu_185_p6 = exitcond_flatten4_reg_181.read();
        }
    } else {
        ap_phi_mux_exitcond_flatten4_phi_fu_185_p6 = exitcond_flatten4_reg_181.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_i_phi_fu_283_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_i_phi_fu_283_p6 = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_i_phi_fu_283_p6 = i_mid2_reg_728.read();
        } else {
            ap_phi_mux_i_phi_fu_283_p6 = i_reg_279.read();
        }
    } else {
        ap_phi_mux_i_phi_fu_283_p6 = i_reg_279.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_indvar_flatten1_phi_fu_269_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_indvar_flatten1_phi_fu_269_p6 = ap_const_lv8_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_indvar_flatten1_phi_fu_269_p6 = indvar_flatten_next1_reg_784.read();
        } else {
            ap_phi_mux_indvar_flatten1_phi_fu_269_p6 = indvar_flatten1_reg_265.read();
        }
    } else {
        ap_phi_mux_indvar_flatten1_phi_fu_269_p6 = indvar_flatten1_reg_265.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_indvar_flatten2_phi_fu_297_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_indvar_flatten2_phi_fu_297_p6 = ap_const_lv11_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_indvar_flatten2_phi_fu_297_p6 = indvar_flatten_next2_reg_769.read();
        } else {
            ap_phi_mux_indvar_flatten2_phi_fu_297_p6 = indvar_flatten2_reg_293.read();
        }
    } else {
        ap_phi_mux_indvar_flatten2_phi_fu_297_p6 = indvar_flatten2_reg_293.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_indvar_flatten_phi_fu_241_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_indvar_flatten_phi_fu_241_p6 = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_indvar_flatten_phi_fu_241_p6 = indvar_flatten_next_reg_779.read();
        } else {
            ap_phi_mux_indvar_flatten_phi_fu_241_p6 = indvar_flatten_reg_237.read();
        }
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_241_p6 = indvar_flatten_reg_237.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_j_phi_fu_255_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_j_phi_fu_255_p6 = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_j_phi_fu_255_p6 = j_mid2_reg_746.read();
        } else {
            ap_phi_mux_j_phi_fu_255_p6 = j_reg_251.read();
        }
    } else {
        ap_phi_mux_j_phi_fu_255_p6 = j_reg_251.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_k_phi_fu_325_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_1)) {
            ap_phi_mux_k_phi_fu_325_p6 = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_0)) {
            ap_phi_mux_k_phi_fu_325_p6 = k_mid2_reg_813.read();
        } else {
            ap_phi_mux_k_phi_fu_325_p6 = k_reg_321.read();
        }
    } else {
        ap_phi_mux_k_phi_fu_325_p6 = k_reg_321.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_k_s_phi_fu_311_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_1)) {
            ap_phi_mux_k_s_phi_fu_311_p6 = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_0)) {
            ap_phi_mux_k_s_phi_fu_311_p6 = tmp_10_reg_847.read();
        } else {
            ap_phi_mux_k_s_phi_fu_311_p6 = k_s_reg_307.read();
        }
    } else {
        ap_phi_mux_k_s_phi_fu_311_p6 = k_s_reg_307.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_l_phi_fu_353_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_reg_804_pp0_iter8_reg.read())) {
            ap_phi_mux_l_phi_fu_353_p6 = ap_const_lv8_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter8_reg.read(), ap_const_lv1_0)) {
            ap_phi_mux_l_phi_fu_353_p6 = l_mid2_reg_858.read();
        } else {
            ap_phi_mux_l_phi_fu_353_p6 = l_reg_349.read();
        }
    } else {
        ap_phi_mux_l_phi_fu_353_p6 = l_reg_349.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_l_s_phi_fu_339_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_reg_804_pp0_iter8_reg.read())) {
            ap_phi_mux_l_s_phi_fu_339_p6 = ap_const_lv8_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter8_reg.read(), ap_const_lv1_0)) {
            ap_phi_mux_l_s_phi_fu_339_p6 = l_1_mid2_reg_863.read();
        } else {
            ap_phi_mux_l_s_phi_fu_339_p6 = l_s_reg_335.read();
        }
    } else {
        ap_phi_mux_l_s_phi_fu_339_p6 = l_s_reg_335.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_m_cast_phi_fu_213_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_m_cast_phi_fu_213_p6 = ap_const_lv2_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_m_cast_phi_fu_213_p6 = m_cast_mid2_reg_757.read();
        } else {
            ap_phi_mux_m_cast_phi_fu_213_p6 = m_cast_reg_209.read();
        }
    } else {
        ap_phi_mux_m_cast_phi_fu_213_p6 = m_cast_reg_209.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_n_phi_fu_227_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_n_phi_fu_227_p6 = ap_const_lv2_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_n_phi_fu_227_p6 = n_1_reg_774.read();
        } else {
            ap_phi_mux_n_phi_fu_227_p6 = n_reg_223.read();
        }
    } else {
        ap_phi_mux_n_phi_fu_227_p6 = n_reg_223.read();
    }
}

void resample_for_conv2::thread_ap_phi_mux_tmp_1_phi_fu_199_p6() {
    if (esl_seteq<1,1,1>(ap_condition_275.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_1)) {
            ap_phi_mux_tmp_1_phi_fu_199_p6 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(exitcond_flatten2_reg_804.read(), ap_const_lv1_0)) {
            ap_phi_mux_tmp_1_phi_fu_199_p6 = tmp_3_reg_789.read();
        } else {
            ap_phi_mux_tmp_1_phi_fu_199_p6 = tmp_1_reg_195.read();
        }
    } else {
        ap_phi_mux_tmp_1_phi_fu_199_p6 = tmp_1_reg_195.read();
    }
}

void resample_for_conv2::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void resample_for_conv2::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to9.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_exitcond_flatten1_fu_539_p2() {
    exitcond_flatten1_fu_539_p2 = (!indvar_flatten_next1_fu_519_p3.read().is_01() || !ap_const_lv8_7E.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_next1_fu_519_p3.read() == ap_const_lv8_7E);
}

void resample_for_conv2::thread_exitcond_flatten2_fu_545_p2() {
    exitcond_flatten2_fu_545_p2 = (!ap_phi_mux_indvar_flatten2_phi_fu_297_p6.read().is_01() || !ap_const_lv11_6E3.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten2_phi_fu_297_p6.read() == ap_const_lv11_6E3);
}

void resample_for_conv2::thread_exitcond_flatten_fu_533_p2() {
    exitcond_flatten_fu_533_p2 = (!indvar_flatten_next_fu_505_p3.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_next_fu_505_p3.read() == ap_const_lv4_9);
}

void resample_for_conv2::thread_exitcond_flatten_mid_fu_389_p2() {
    exitcond_flatten_mid_fu_389_p2 = (ap_phi_mux_exitcond_flatten4_phi_fu_185_p6.read() & not_exitcond_flatten_fu_377_p2.read());
}

void resample_for_conv2::thread_exitcond_flatten_not_fu_423_p2() {
    exitcond_flatten_not_fu_423_p2 = (ap_phi_mux_exitcond_flatten4_phi_fu_185_p6.read() ^ ap_const_lv1_1);
}

void resample_for_conv2::thread_grp_fu_631_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
        grp_fu_631_ce = ap_const_logic_1;
    } else {
        grp_fu_631_ce = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_grp_fu_715_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
        grp_fu_715_ce = ap_const_logic_1;
    } else {
        grp_fu_715_ce = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_grp_fu_715_p0() {
    grp_fu_715_p0 =  (sc_lv<9>) (ap_const_lv11_C4);
}

void resample_for_conv2::thread_grp_fu_715_p1() {
    grp_fu_715_p1 =  (sc_lv<4>) (grp_fu_715_p10.read());
}

void resample_for_conv2::thread_grp_fu_715_p10() {
    grp_fu_715_p10 = esl_zext<11,4>(grp_fu_631_p2.read());
}

void resample_for_conv2::thread_grp_fu_715_p2() {
    grp_fu_715_p2 =  (sc_lv<8>) (grp_fu_715_p20.read());
}

void resample_for_conv2::thread_grp_fu_715_p20() {
    grp_fu_715_p20 = esl_zext<11,8>(l_1_mid2_reg_863.read());
}

void resample_for_conv2::thread_i_1_fu_363_p2() {
    i_1_fu_363_p2 = (!ap_const_lv4_1.is_01() || !ap_phi_mux_i_phi_fu_283_p6.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ap_phi_mux_i_phi_fu_283_p6.read()));
}

void resample_for_conv2::thread_i_mid2_fu_395_p3() {
    i_mid2_fu_395_p3 = (!ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read()[0].is_01())? sc_lv<4>(): ((ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read()[0].to_bool())? i_1_fu_363_p2.read(): ap_phi_mux_i_phi_fu_283_p6.read());
}

void resample_for_conv2::thread_indvar_flatten17_op_fu_513_p2() {
    indvar_flatten17_op_fu_513_p2 = (!ap_phi_mux_indvar_flatten1_phi_fu_269_p6.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ap_phi_mux_indvar_flatten1_phi_fu_269_p6.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void resample_for_conv2::thread_indvar_flatten_next1_fu_519_p3() {
    indvar_flatten_next1_fu_519_p3 = (!ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read()[0].is_01())? sc_lv<8>(): ((ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read()[0].to_bool())? ap_const_lv8_1: indvar_flatten17_op_fu_513_p2.read());
}

void resample_for_conv2::thread_indvar_flatten_next2_fu_487_p2() {
    indvar_flatten_next2_fu_487_p2 = (!ap_const_lv11_1.is_01() || !ap_phi_mux_indvar_flatten2_phi_fu_297_p6.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_1) + sc_biguint<11>(ap_phi_mux_indvar_flatten2_phi_fu_297_p6.read()));
}

void resample_for_conv2::thread_indvar_flatten_next_fu_505_p3() {
    indvar_flatten_next_fu_505_p3 = (!tmp_fu_409_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_fu_409_p2.read()[0].to_bool())? ap_const_lv4_1: indvar_flatten_op_fu_499_p2.read());
}

void resample_for_conv2::thread_indvar_flatten_op_fu_499_p2() {
    indvar_flatten_op_fu_499_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_241_p6.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_indvar_flatten_phi_fu_241_p6.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void resample_for_conv2::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_804_pp0_iter1_reg.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_j_1_fu_403_p2() {
    j_1_fu_403_p2 = (!ap_const_lv4_1.is_01() || !j_mid_fu_369_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(j_mid_fu_369_p3.read()));
}

void resample_for_conv2::thread_j_mid2_fu_441_p3() {
    j_mid2_fu_441_p3 = (!exitcond_flatten_mid_fu_389_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten_mid_fu_389_p2.read()[0].to_bool())? j_1_fu_403_p2.read(): j_mid_fu_369_p3.read());
}

void resample_for_conv2::thread_j_mid_fu_369_p3() {
    j_mid_fu_369_p3 = (!ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read()[0].is_01())? sc_lv<4>(): ((ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_j_phi_fu_255_p6.read());
}

void resample_for_conv2::thread_k_1_mid2_fu_571_p3() {
    k_1_mid2_fu_571_p3 = (!tmp_3_mid1_reg_740.read()[0].is_01())? sc_lv<4>(): ((tmp_3_mid1_reg_740.read()[0].to_bool())? k_2_dup_fu_565_p2.read(): k_1_mid_fu_558_p3.read());
}

void resample_for_conv2::thread_k_1_mid_fu_558_p3() {
    k_1_mid_fu_558_p3 = (!tmp_reg_734.read()[0].is_01())? sc_lv<4>(): ((tmp_reg_734.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_k_s_phi_fu_311_p6.read());
}

void resample_for_conv2::thread_k_2_dup_fu_565_p2() {
    k_2_dup_fu_565_p2 = (!ap_const_lv4_3.is_01() || !k_mid_fu_551_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_3) + sc_biguint<4>(k_mid_fu_551_p3.read()));
}

void resample_for_conv2::thread_k_mid2_fu_581_p3() {
    k_mid2_fu_581_p3 = (!tmp_3_mid1_reg_740.read()[0].is_01())? sc_lv<4>(): ((tmp_3_mid1_reg_740.read()[0].to_bool())? k_2_dup_fu_565_p2.read(): k_mid_fu_551_p3.read());
}

void resample_for_conv2::thread_k_mid_fu_551_p3() {
    k_mid_fu_551_p3 = (!tmp_reg_734.read()[0].is_01())? sc_lv<4>(): ((tmp_reg_734.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_k_phi_fu_325_p6.read());
}

void resample_for_conv2::thread_l_1_mid2_fu_694_p3() {
    l_1_mid2_fu_694_p3 = (!exitcond_flatten_mid_reg_723_pp0_iter7_reg.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten_mid_reg_723_pp0_iter7_reg.read()[0].to_bool())? tmp_2_fu_688_p2.read(): l_1_mid_fu_672_p3.read());
}

void resample_for_conv2::thread_l_1_mid_fu_672_p3() {
    l_1_mid_fu_672_p3 = (!exitcond_flatten3_reg_166_pp0_iter7_reg.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten3_reg_166_pp0_iter7_reg.read()[0].to_bool())? l_2_dup_fu_666_p2.read(): ap_phi_mux_l_s_phi_fu_339_p6.read());
}

void resample_for_conv2::thread_l_2_dup_fu_666_p2() {
    l_2_dup_fu_666_p2 = (!ap_const_lv8_E.is_01() || !ap_phi_mux_l_phi_fu_353_p6.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_E) + sc_biguint<8>(ap_phi_mux_l_phi_fu_353_p6.read()));
}

void resample_for_conv2::thread_l_mid2_fu_680_p3() {
    l_mid2_fu_680_p3 = (!exitcond_flatten3_reg_166_pp0_iter7_reg.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten3_reg_166_pp0_iter7_reg.read()[0].to_bool())? l_2_dup_fu_666_p2.read(): ap_phi_mux_l_phi_fu_353_p6.read());
}

void resample_for_conv2::thread_m_cast_mid2_cast_fu_578_p1() {
    m_cast_mid2_cast_fu_578_p1 = esl_zext<4,2>(m_cast_mid2_reg_757.read());
}

void resample_for_conv2::thread_m_cast_mid2_fu_475_p3() {
    m_cast_mid2_fu_475_p3 = (!tmp_3_mid1_fu_435_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_3_mid1_fu_435_p2.read()[0].to_bool())? m_fu_449_p2.read(): m_mid_fu_415_p3.read());
}

void resample_for_conv2::thread_m_fu_449_p2() {
    m_fu_449_p2 = (!ap_const_lv2_1.is_01() || !m_mid_fu_415_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(m_mid_fu_415_p3.read()));
}

void resample_for_conv2::thread_m_mid_fu_415_p3() {
    m_mid_fu_415_p3 = (!tmp_fu_409_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_fu_409_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_m_cast_phi_fu_213_p6.read());
}

void resample_for_conv2::thread_n_1_fu_493_p2() {
    n_1_fu_493_p2 = (!n_mid2_fu_467_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(n_mid2_fu_467_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void resample_for_conv2::thread_n_cast_fu_588_p1() {
    n_cast_fu_588_p1 = esl_zext<4,2>(n_mid2_reg_752.read());
}

void resample_for_conv2::thread_n_mid2_fu_467_p3() {
    n_mid2_fu_467_p3 = (!tmp_5_fu_461_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_5_fu_461_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_n_phi_fu_227_p6.read());
}

void resample_for_conv2::thread_newIndex_trunc_fu_611_p2() {
    newIndex_trunc_fu_611_p2 = (!tmp_7_reg_764.read().is_01() || !m_cast_mid2_reg_757.read().is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_7_reg_764.read()) + sc_biguint<2>(m_cast_mid2_reg_757.read()));
}

void resample_for_conv2::thread_not_exitcond_flatten_1_fu_429_p2() {
    not_exitcond_flatten_1_fu_429_p2 = (ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read() | exitcond_flatten_not_fu_423_p2.read());
}

void resample_for_conv2::thread_not_exitcond_flatten_fu_377_p2() {
    not_exitcond_flatten_fu_377_p2 = (ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read() ^ ap_const_lv1_1);
}

void resample_for_conv2::thread_resampled_0_V_address0() {
    resampled_0_V_address0 =  (sc_lv<10>) (tmp_17_cast_fu_708_p1.read());
}

void resample_for_conv2::thread_resampled_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()))) {
        resampled_0_V_ce0 = ap_const_logic_1;
    } else {
        resampled_0_V_ce0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_resampled_0_V_d0() {
    resampled_0_V_d0 = tmp_12_reg_852_pp0_iter9_reg.read();
}

void resample_for_conv2::thread_resampled_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_15_reg_843_pp0_iter9_reg.read()))) {
        resampled_0_V_we0 = ap_const_logic_1;
    } else {
        resampled_0_V_we0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_resampled_1_V_address0() {
    resampled_1_V_address0 =  (sc_lv<10>) (tmp_17_cast_fu_708_p1.read());
}

void resample_for_conv2::thread_resampled_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()))) {
        resampled_1_V_ce0 = ap_const_logic_1;
    } else {
        resampled_1_V_ce0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_resampled_1_V_d0() {
    resampled_1_V_d0 = tmp_12_reg_852_pp0_iter9_reg.read();
}

void resample_for_conv2::thread_resampled_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(tmp_15_reg_843_pp0_iter9_reg.read(), ap_const_lv1_0))) {
        resampled_1_V_we0 = ap_const_logic_1;
    } else {
        resampled_1_V_we0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_rewind_ap_ready() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten2_fu_545_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, rewind_ap_ready_reg.read()))) {
        rewind_ap_ready = ap_const_logic_1;
    } else {
        rewind_ap_ready = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_rewind_enable() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, rewind_ap_ready_reg.read()))) {
        rewind_enable = ap_const_logic_1;
    } else {
        rewind_enable = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_square_image_0_V_address0() {
    square_image_0_V_address0 =  (sc_lv<6>) (tmp_11_fu_623_p1.read());
}

void resample_for_conv2::thread_square_image_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        square_image_0_V_ce0 = ap_const_logic_1;
    } else {
        square_image_0_V_ce0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_square_image_1_V_address0() {
    square_image_1_V_address0 =  (sc_lv<6>) (tmp_11_fu_623_p1.read());
}

void resample_for_conv2::thread_square_image_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        square_image_1_V_ce0 = ap_const_logic_1;
    } else {
        square_image_1_V_ce0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_square_image_2_V_address0() {
    square_image_2_V_address0 =  (sc_lv<6>) (tmp_11_fu_623_p1.read());
}

void resample_for_conv2::thread_square_image_2_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        square_image_2_V_ce0 = ap_const_logic_1;
    } else {
        square_image_2_V_ce0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_square_image_3_V_address0() {
    square_image_3_V_address0 =  (sc_lv<6>) (tmp_11_fu_623_p1.read());
}

void resample_for_conv2::thread_square_image_3_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        square_image_3_V_ce0 = ap_const_logic_1;
    } else {
        square_image_3_V_ce0 = ap_const_logic_0;
    }
}

void resample_for_conv2::thread_tmp_10_fu_643_p2() {
    tmp_10_fu_643_p2 = (!k_1_mid2_fu_571_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_1_mid2_fu_571_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void resample_for_conv2::thread_tmp_11_fu_623_p1() {
    tmp_11_fu_623_p1 = esl_zext<64,6>(tmp_9_fu_615_p3.read());
}

void resample_for_conv2::thread_tmp_12_fu_652_p5() {
    tmp_12_fu_652_p5 = esl_zext<32,2>(arrayNo_reg_818.read());
}

void resample_for_conv2::thread_tmp_15_fu_637_p2() {
    tmp_15_fu_637_p2 = (!k_1_mid2_fu_571_p3.read().is_01() || !ap_const_lv4_5.is_01())? sc_lv<1>(): (sc_biguint<4>(k_1_mid2_fu_571_p3.read()) < sc_biguint<4>(ap_const_lv4_5));
}

void resample_for_conv2::thread_tmp_17_cast_fu_708_p1() {
    tmp_17_cast_fu_708_p1 = esl_sext<64,11>(tmp_14_reg_874.read());
}

void resample_for_conv2::thread_tmp_2_fu_688_p2() {
    tmp_2_fu_688_p2 = (!ap_const_lv8_1.is_01() || !l_1_mid_fu_672_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(l_1_mid_fu_672_p3.read()));
}

void resample_for_conv2::thread_tmp_3_fu_527_p2() {
    tmp_3_fu_527_p2 = (!n_1_fu_493_p2.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(n_1_fu_493_p2.read() == ap_const_lv2_3);
}

void resample_for_conv2::thread_tmp_3_mid1_fu_435_p2() {
    tmp_3_mid1_fu_435_p2 = (tmp_3_mid_fu_383_p2.read() & not_exitcond_flatten_1_fu_429_p2.read());
}

void resample_for_conv2::thread_tmp_3_mid_fu_383_p2() {
    tmp_3_mid_fu_383_p2 = (ap_phi_mux_tmp_1_phi_fu_199_p6.read() & not_exitcond_flatten_fu_377_p2.read());
}

void resample_for_conv2::thread_tmp_4_fu_455_p2() {
    tmp_4_fu_455_p2 = (tmp_3_mid1_fu_435_p2.read() | exitcond_flatten_mid_fu_389_p2.read());
}

void resample_for_conv2::thread_tmp_5_fu_461_p2() {
    tmp_5_fu_461_p2 = (tmp_4_fu_455_p2.read() | ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read());
}

void resample_for_conv2::thread_tmp_6_fu_591_p2() {
    tmp_6_fu_591_p2 = (!n_cast_fu_588_p1.read().is_01() || !j_mid2_reg_746.read().is_01())? sc_lv<4>(): (sc_biguint<4>(n_cast_fu_588_p1.read()) + sc_biguint<4>(j_mid2_reg_746.read()));
}

void resample_for_conv2::thread_tmp_7_fu_483_p1() {
    tmp_7_fu_483_p1 = i_mid2_fu_395_p3.read().range(2-1, 0);
}

void resample_for_conv2::thread_tmp_8_fu_596_p2() {
    tmp_8_fu_596_p2 = (!m_cast_mid2_cast_fu_578_p1.read().is_01() || !i_mid2_reg_728.read().is_01())? sc_lv<4>(): (sc_biguint<4>(m_cast_mid2_cast_fu_578_p1.read()) + sc_biguint<4>(i_mid2_reg_728.read()));
}

void resample_for_conv2::thread_tmp_9_fu_615_p3() {
    tmp_9_fu_615_p3 = esl_concat<2,4>(newIndex_trunc_fu_611_p2.read(), tmp_6_fu_591_p2.read());
}

void resample_for_conv2::thread_tmp_fu_409_p2() {
    tmp_fu_409_p2 = (exitcond_flatten_mid_fu_389_p2.read() | ap_phi_mux_exitcond_flatten3_phi_fu_170_p6.read());
}

void resample_for_conv2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

