// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_features_0_V_address0,
        in_features_0_V_ce0,
        in_features_0_V_q0,
        in_features_1_V_address0,
        in_features_1_V_ce0,
        in_features_1_V_q0,
        in_features_2_V_address0,
        in_features_2_V_ce0,
        in_features_2_V_q0,
        in_features_3_V_address0,
        in_features_3_V_ce0,
        in_features_3_V_q0,
        in_features_4_V_address0,
        in_features_4_V_ce0,
        in_features_4_V_q0,
        in_features_5_V_address0,
        in_features_5_V_ce0,
        in_features_5_V_q0,
        in_features_6_V_address0,
        in_features_6_V_ce0,
        in_features_6_V_q0,
        in_features_7_V_address0,
        in_features_7_V_ce0,
        in_features_7_V_q0,
        in_features_8_V_address0,
        in_features_8_V_ce0,
        in_features_8_V_q0,
        in_features_9_V_address0,
        in_features_9_V_ce0,
        in_features_9_V_q0,
        in_features_10_V_address0,
        in_features_10_V_ce0,
        in_features_10_V_q0,
        in_features_11_V_address0,
        in_features_11_V_ce0,
        in_features_11_V_q0,
        in_features_12_V_address0,
        in_features_12_V_ce0,
        in_features_12_V_q0,
        in_features_13_V_address0,
        in_features_13_V_ce0,
        in_features_13_V_q0,
        in_features_14_V_address0,
        in_features_14_V_ce0,
        in_features_14_V_q0,
        in_features_15_V_address0,
        in_features_15_V_ce0,
        in_features_15_V_q0,
        in_features_16_V_address0,
        in_features_16_V_ce0,
        in_features_16_V_q0,
        in_features_17_V_address0,
        in_features_17_V_ce0,
        in_features_17_V_q0,
        in_features_18_V_address0,
        in_features_18_V_ce0,
        in_features_18_V_q0,
        in_features_19_V_address0,
        in_features_19_V_ce0,
        in_features_19_V_q0,
        in_features_20_V_address0,
        in_features_20_V_ce0,
        in_features_20_V_q0,
        in_features_21_V_address0,
        in_features_21_V_ce0,
        in_features_21_V_q0,
        in_features_22_V_address0,
        in_features_22_V_ce0,
        in_features_22_V_q0,
        in_features_23_V_address0,
        in_features_23_V_ce0,
        in_features_23_V_q0,
        in_features_24_V_address0,
        in_features_24_V_ce0,
        in_features_24_V_q0,
        in_features_25_V_address0,
        in_features_25_V_ce0,
        in_features_25_V_q0,
        in_features_26_V_address0,
        in_features_26_V_ce0,
        in_features_26_V_q0,
        in_features_27_V_address0,
        in_features_27_V_ce0,
        in_features_27_V_q0,
        activations_0_V_address0,
        activations_0_V_ce0,
        activations_0_V_we0,
        activations_0_V_d0,
        activations_1_V_address0,
        activations_1_V_ce0,
        activations_1_V_we0,
        activations_1_V_d0,
        activations_2_V_address0,
        activations_2_V_ce0,
        activations_2_V_we0,
        activations_2_V_d0,
        activations_3_V_address0,
        activations_3_V_ce0,
        activations_3_V_we0,
        activations_3_V_d0,
        activations_4_V_address0,
        activations_4_V_ce0,
        activations_4_V_we0,
        activations_4_V_d0,
        activations_5_V_address0,
        activations_5_V_ce0,
        activations_5_V_we0,
        activations_5_V_d0,
        activations_6_V_address0,
        activations_6_V_ce0,
        activations_6_V_we0,
        activations_6_V_d0,
        activations_7_V_address0,
        activations_7_V_ce0,
        activations_7_V_we0,
        activations_7_V_d0,
        activations_8_V_address0,
        activations_8_V_ce0,
        activations_8_V_we0,
        activations_8_V_d0,
        activations_9_V_address0,
        activations_9_V_ce0,
        activations_9_V_we0,
        activations_9_V_d0,
        activations_10_V_address0,
        activations_10_V_ce0,
        activations_10_V_we0,
        activations_10_V_d0,
        activations_11_V_address0,
        activations_11_V_ce0,
        activations_11_V_we0,
        activations_11_V_d0,
        activations_12_V_address0,
        activations_12_V_ce0,
        activations_12_V_we0,
        activations_12_V_d0,
        activations_13_V_address0,
        activations_13_V_ce0,
        activations_13_V_we0,
        activations_13_V_d0,
        activations_14_V_address0,
        activations_14_V_ce0,
        activations_14_V_we0,
        activations_14_V_d0,
        activations_15_V_address0,
        activations_15_V_ce0,
        activations_15_V_we0,
        activations_15_V_d0,
        activations_16_V_address0,
        activations_16_V_ce0,
        activations_16_V_we0,
        activations_16_V_d0,
        activations_17_V_address0,
        activations_17_V_ce0,
        activations_17_V_we0,
        activations_17_V_d0,
        activations_18_V_address0,
        activations_18_V_ce0,
        activations_18_V_we0,
        activations_18_V_d0,
        activations_19_V_address0,
        activations_19_V_ce0,
        activations_19_V_we0,
        activations_19_V_d0,
        activations_20_V_address0,
        activations_20_V_ce0,
        activations_20_V_we0,
        activations_20_V_d0,
        activations_21_V_address0,
        activations_21_V_ce0,
        activations_21_V_we0,
        activations_21_V_d0,
        activations_22_V_address0,
        activations_22_V_ce0,
        activations_22_V_we0,
        activations_22_V_d0,
        activations_23_V_address0,
        activations_23_V_ce0,
        activations_23_V_we0,
        activations_23_V_d0,
        activations_24_V_address0,
        activations_24_V_ce0,
        activations_24_V_we0,
        activations_24_V_d0,
        activations_25_V_address0,
        activations_25_V_ce0,
        activations_25_V_we0,
        activations_25_V_d0,
        activations_26_V_address0,
        activations_26_V_ce0,
        activations_26_V_we0,
        activations_26_V_d0,
        activations_27_V_address0,
        activations_27_V_ce0,
        activations_27_V_we0,
        activations_27_V_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [4:0] in_features_0_V_address0;
output   in_features_0_V_ce0;
input  [47:0] in_features_0_V_q0;
output  [4:0] in_features_1_V_address0;
output   in_features_1_V_ce0;
input  [47:0] in_features_1_V_q0;
output  [4:0] in_features_2_V_address0;
output   in_features_2_V_ce0;
input  [47:0] in_features_2_V_q0;
output  [4:0] in_features_3_V_address0;
output   in_features_3_V_ce0;
input  [47:0] in_features_3_V_q0;
output  [4:0] in_features_4_V_address0;
output   in_features_4_V_ce0;
input  [47:0] in_features_4_V_q0;
output  [4:0] in_features_5_V_address0;
output   in_features_5_V_ce0;
input  [47:0] in_features_5_V_q0;
output  [4:0] in_features_6_V_address0;
output   in_features_6_V_ce0;
input  [47:0] in_features_6_V_q0;
output  [4:0] in_features_7_V_address0;
output   in_features_7_V_ce0;
input  [47:0] in_features_7_V_q0;
output  [4:0] in_features_8_V_address0;
output   in_features_8_V_ce0;
input  [47:0] in_features_8_V_q0;
output  [4:0] in_features_9_V_address0;
output   in_features_9_V_ce0;
input  [47:0] in_features_9_V_q0;
output  [4:0] in_features_10_V_address0;
output   in_features_10_V_ce0;
input  [47:0] in_features_10_V_q0;
output  [4:0] in_features_11_V_address0;
output   in_features_11_V_ce0;
input  [47:0] in_features_11_V_q0;
output  [4:0] in_features_12_V_address0;
output   in_features_12_V_ce0;
input  [47:0] in_features_12_V_q0;
output  [4:0] in_features_13_V_address0;
output   in_features_13_V_ce0;
input  [47:0] in_features_13_V_q0;
output  [4:0] in_features_14_V_address0;
output   in_features_14_V_ce0;
input  [47:0] in_features_14_V_q0;
output  [4:0] in_features_15_V_address0;
output   in_features_15_V_ce0;
input  [47:0] in_features_15_V_q0;
output  [4:0] in_features_16_V_address0;
output   in_features_16_V_ce0;
input  [47:0] in_features_16_V_q0;
output  [4:0] in_features_17_V_address0;
output   in_features_17_V_ce0;
input  [47:0] in_features_17_V_q0;
output  [4:0] in_features_18_V_address0;
output   in_features_18_V_ce0;
input  [47:0] in_features_18_V_q0;
output  [4:0] in_features_19_V_address0;
output   in_features_19_V_ce0;
input  [47:0] in_features_19_V_q0;
output  [4:0] in_features_20_V_address0;
output   in_features_20_V_ce0;
input  [47:0] in_features_20_V_q0;
output  [4:0] in_features_21_V_address0;
output   in_features_21_V_ce0;
input  [47:0] in_features_21_V_q0;
output  [4:0] in_features_22_V_address0;
output   in_features_22_V_ce0;
input  [47:0] in_features_22_V_q0;
output  [4:0] in_features_23_V_address0;
output   in_features_23_V_ce0;
input  [47:0] in_features_23_V_q0;
output  [4:0] in_features_24_V_address0;
output   in_features_24_V_ce0;
input  [47:0] in_features_24_V_q0;
output  [4:0] in_features_25_V_address0;
output   in_features_25_V_ce0;
input  [47:0] in_features_25_V_q0;
output  [4:0] in_features_26_V_address0;
output   in_features_26_V_ce0;
input  [47:0] in_features_26_V_q0;
output  [4:0] in_features_27_V_address0;
output   in_features_27_V_ce0;
input  [47:0] in_features_27_V_q0;
output  [4:0] activations_0_V_address0;
output   activations_0_V_ce0;
output   activations_0_V_we0;
output  [47:0] activations_0_V_d0;
output  [4:0] activations_1_V_address0;
output   activations_1_V_ce0;
output   activations_1_V_we0;
output  [47:0] activations_1_V_d0;
output  [4:0] activations_2_V_address0;
output   activations_2_V_ce0;
output   activations_2_V_we0;
output  [47:0] activations_2_V_d0;
output  [4:0] activations_3_V_address0;
output   activations_3_V_ce0;
output   activations_3_V_we0;
output  [47:0] activations_3_V_d0;
output  [4:0] activations_4_V_address0;
output   activations_4_V_ce0;
output   activations_4_V_we0;
output  [47:0] activations_4_V_d0;
output  [4:0] activations_5_V_address0;
output   activations_5_V_ce0;
output   activations_5_V_we0;
output  [47:0] activations_5_V_d0;
output  [4:0] activations_6_V_address0;
output   activations_6_V_ce0;
output   activations_6_V_we0;
output  [47:0] activations_6_V_d0;
output  [4:0] activations_7_V_address0;
output   activations_7_V_ce0;
output   activations_7_V_we0;
output  [47:0] activations_7_V_d0;
output  [4:0] activations_8_V_address0;
output   activations_8_V_ce0;
output   activations_8_V_we0;
output  [47:0] activations_8_V_d0;
output  [4:0] activations_9_V_address0;
output   activations_9_V_ce0;
output   activations_9_V_we0;
output  [47:0] activations_9_V_d0;
output  [4:0] activations_10_V_address0;
output   activations_10_V_ce0;
output   activations_10_V_we0;
output  [47:0] activations_10_V_d0;
output  [4:0] activations_11_V_address0;
output   activations_11_V_ce0;
output   activations_11_V_we0;
output  [47:0] activations_11_V_d0;
output  [4:0] activations_12_V_address0;
output   activations_12_V_ce0;
output   activations_12_V_we0;
output  [47:0] activations_12_V_d0;
output  [4:0] activations_13_V_address0;
output   activations_13_V_ce0;
output   activations_13_V_we0;
output  [47:0] activations_13_V_d0;
output  [4:0] activations_14_V_address0;
output   activations_14_V_ce0;
output   activations_14_V_we0;
output  [47:0] activations_14_V_d0;
output  [4:0] activations_15_V_address0;
output   activations_15_V_ce0;
output   activations_15_V_we0;
output  [47:0] activations_15_V_d0;
output  [4:0] activations_16_V_address0;
output   activations_16_V_ce0;
output   activations_16_V_we0;
output  [47:0] activations_16_V_d0;
output  [4:0] activations_17_V_address0;
output   activations_17_V_ce0;
output   activations_17_V_we0;
output  [47:0] activations_17_V_d0;
output  [4:0] activations_18_V_address0;
output   activations_18_V_ce0;
output   activations_18_V_we0;
output  [47:0] activations_18_V_d0;
output  [4:0] activations_19_V_address0;
output   activations_19_V_ce0;
output   activations_19_V_we0;
output  [47:0] activations_19_V_d0;
output  [4:0] activations_20_V_address0;
output   activations_20_V_ce0;
output   activations_20_V_we0;
output  [47:0] activations_20_V_d0;
output  [4:0] activations_21_V_address0;
output   activations_21_V_ce0;
output   activations_21_V_we0;
output  [47:0] activations_21_V_d0;
output  [4:0] activations_22_V_address0;
output   activations_22_V_ce0;
output   activations_22_V_we0;
output  [47:0] activations_22_V_d0;
output  [4:0] activations_23_V_address0;
output   activations_23_V_ce0;
output   activations_23_V_we0;
output  [47:0] activations_23_V_d0;
output  [4:0] activations_24_V_address0;
output   activations_24_V_ce0;
output   activations_24_V_we0;
output  [47:0] activations_24_V_d0;
output  [4:0] activations_25_V_address0;
output   activations_25_V_ce0;
output   activations_25_V_we0;
output  [47:0] activations_25_V_d0;
output  [4:0] activations_26_V_address0;
output   activations_26_V_ce0;
output   activations_26_V_we0;
output  [47:0] activations_26_V_d0;
output  [4:0] activations_27_V_address0;
output   activations_27_V_ce0;
output   activations_27_V_we0;
output  [47:0] activations_27_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_features_0_V_ce0;
reg in_features_1_V_ce0;
reg in_features_2_V_ce0;
reg in_features_3_V_ce0;
reg in_features_4_V_ce0;
reg in_features_5_V_ce0;
reg in_features_6_V_ce0;
reg in_features_7_V_ce0;
reg in_features_8_V_ce0;
reg in_features_9_V_ce0;
reg in_features_10_V_ce0;
reg in_features_11_V_ce0;
reg in_features_12_V_ce0;
reg in_features_13_V_ce0;
reg in_features_14_V_ce0;
reg in_features_15_V_ce0;
reg in_features_16_V_ce0;
reg in_features_17_V_ce0;
reg in_features_18_V_ce0;
reg in_features_19_V_ce0;
reg in_features_20_V_ce0;
reg in_features_21_V_ce0;
reg in_features_22_V_ce0;
reg in_features_23_V_ce0;
reg in_features_24_V_ce0;
reg in_features_25_V_ce0;
reg in_features_26_V_ce0;
reg in_features_27_V_ce0;
reg activations_0_V_ce0;
reg activations_0_V_we0;
reg[47:0] activations_0_V_d0;
reg activations_1_V_ce0;
reg activations_1_V_we0;
reg[47:0] activations_1_V_d0;
reg activations_2_V_ce0;
reg activations_2_V_we0;
reg[47:0] activations_2_V_d0;
reg activations_3_V_ce0;
reg activations_3_V_we0;
reg[47:0] activations_3_V_d0;
reg activations_4_V_ce0;
reg activations_4_V_we0;
reg[47:0] activations_4_V_d0;
reg activations_5_V_ce0;
reg activations_5_V_we0;
reg[47:0] activations_5_V_d0;
reg activations_6_V_ce0;
reg activations_6_V_we0;
reg[47:0] activations_6_V_d0;
reg activations_7_V_ce0;
reg activations_7_V_we0;
reg[47:0] activations_7_V_d0;
reg activations_8_V_ce0;
reg activations_8_V_we0;
reg[47:0] activations_8_V_d0;
reg activations_9_V_ce0;
reg activations_9_V_we0;
reg[47:0] activations_9_V_d0;
reg activations_10_V_ce0;
reg activations_10_V_we0;
reg[47:0] activations_10_V_d0;
reg activations_11_V_ce0;
reg activations_11_V_we0;
reg[47:0] activations_11_V_d0;
reg activations_12_V_ce0;
reg activations_12_V_we0;
reg[47:0] activations_12_V_d0;
reg activations_13_V_ce0;
reg activations_13_V_we0;
reg[47:0] activations_13_V_d0;
reg activations_14_V_ce0;
reg activations_14_V_we0;
reg[47:0] activations_14_V_d0;
reg activations_15_V_ce0;
reg activations_15_V_we0;
reg[47:0] activations_15_V_d0;
reg activations_16_V_ce0;
reg activations_16_V_we0;
reg[47:0] activations_16_V_d0;
reg activations_17_V_ce0;
reg activations_17_V_we0;
reg[47:0] activations_17_V_d0;
reg activations_18_V_ce0;
reg activations_18_V_we0;
reg[47:0] activations_18_V_d0;
reg activations_19_V_ce0;
reg activations_19_V_we0;
reg[47:0] activations_19_V_d0;
reg activations_20_V_ce0;
reg activations_20_V_we0;
reg[47:0] activations_20_V_d0;
reg activations_21_V_ce0;
reg activations_21_V_we0;
reg[47:0] activations_21_V_d0;
reg activations_22_V_ce0;
reg activations_22_V_we0;
reg[47:0] activations_22_V_d0;
reg activations_23_V_ce0;
reg activations_23_V_we0;
reg[47:0] activations_23_V_d0;
reg activations_24_V_ce0;
reg activations_24_V_we0;
reg[47:0] activations_24_V_d0;
reg activations_25_V_ce0;
reg activations_25_V_we0;
reg[47:0] activations_25_V_d0;
reg activations_26_V_ce0;
reg activations_26_V_we0;
reg[47:0] activations_26_V_d0;
reg activations_27_V_ce0;
reg activations_27_V_we0;
reg[47:0] activations_27_V_d0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] indvar_flatten_reg_954;
reg   [4:0] j_reg_965;
reg   [4:0] k_reg_976;
wire   [0:0] exitcond_flatten_fu_987_p2;
reg   [0:0] exitcond_flatten_reg_1131;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_flatten_reg_1131_pp0_iter1_reg;
wire   [9:0] indvar_flatten_next_fu_993_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [4:0] j_mid2_fu_1019_p3;
reg   [4:0] j_mid2_reg_1140;
reg   [4:0] j_mid2_reg_1140_pp0_iter1_reg;
wire   [63:0] tmp_3_fu_1027_p1;
reg   [63:0] tmp_3_reg_1146;
reg   [63:0] tmp_3_reg_1146_pp0_iter1_reg;
wire   [4:0] k_1_fu_1059_p2;
wire   [47:0] tmp_9_fu_1065_p30;
reg   [47:0] tmp_9_reg_1323;
reg    ap_block_state1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg   [4:0] ap_phi_mux_j_phi_fu_969_p4;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_4_fu_1126_p2;
wire   [0:0] tmp_5_fu_1005_p2;
wire   [4:0] j_1_fu_999_p2;
wire   [4:0] k_mid2_fu_1011_p3;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_965;
reg    ap_condition_968;
reg    ap_condition_971;
reg    ap_condition_974;
reg    ap_condition_977;
reg    ap_condition_980;
reg    ap_condition_983;
reg    ap_condition_986;
reg    ap_condition_989;
reg    ap_condition_992;
reg    ap_condition_995;
reg    ap_condition_998;
reg    ap_condition_1001;
reg    ap_condition_1004;
reg    ap_condition_1007;
reg    ap_condition_1010;
reg    ap_condition_1013;
reg    ap_condition_1016;
reg    ap_condition_1019;
reg    ap_condition_850;
reg    ap_condition_861;
reg    ap_condition_1026;
reg    ap_condition_1029;
reg    ap_condition_1032;
reg    ap_condition_1035;
reg    ap_condition_1038;
reg    ap_condition_1041;
reg    ap_condition_1044;
reg    ap_condition_1047;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

CNN_mux_285_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 48 ),
    .din1_WIDTH( 48 ),
    .din2_WIDTH( 48 ),
    .din3_WIDTH( 48 ),
    .din4_WIDTH( 48 ),
    .din5_WIDTH( 48 ),
    .din6_WIDTH( 48 ),
    .din7_WIDTH( 48 ),
    .din8_WIDTH( 48 ),
    .din9_WIDTH( 48 ),
    .din10_WIDTH( 48 ),
    .din11_WIDTH( 48 ),
    .din12_WIDTH( 48 ),
    .din13_WIDTH( 48 ),
    .din14_WIDTH( 48 ),
    .din15_WIDTH( 48 ),
    .din16_WIDTH( 48 ),
    .din17_WIDTH( 48 ),
    .din18_WIDTH( 48 ),
    .din19_WIDTH( 48 ),
    .din20_WIDTH( 48 ),
    .din21_WIDTH( 48 ),
    .din22_WIDTH( 48 ),
    .din23_WIDTH( 48 ),
    .din24_WIDTH( 48 ),
    .din25_WIDTH( 48 ),
    .din26_WIDTH( 48 ),
    .din27_WIDTH( 48 ),
    .din28_WIDTH( 5 ),
    .dout_WIDTH( 48 ))
CNN_mux_285_48_1_1_U306(
    .din0(in_features_0_V_q0),
    .din1(in_features_1_V_q0),
    .din2(in_features_2_V_q0),
    .din3(in_features_3_V_q0),
    .din4(in_features_4_V_q0),
    .din5(in_features_5_V_q0),
    .din6(in_features_6_V_q0),
    .din7(in_features_7_V_q0),
    .din8(in_features_8_V_q0),
    .din9(in_features_9_V_q0),
    .din10(in_features_10_V_q0),
    .din11(in_features_11_V_q0),
    .din12(in_features_12_V_q0),
    .din13(in_features_13_V_q0),
    .din14(in_features_14_V_q0),
    .din15(in_features_15_V_q0),
    .din16(in_features_16_V_q0),
    .din17(in_features_17_V_q0),
    .din18(in_features_18_V_q0),
    .din19(in_features_19_V_q0),
    .din20(in_features_20_V_q0),
    .din21(in_features_21_V_q0),
    .din22(in_features_22_V_q0),
    .din23(in_features_23_V_q0),
    .din24(in_features_24_V_q0),
    .din25(in_features_25_V_q0),
    .din26(in_features_26_V_q0),
    .din27(in_features_27_V_q0),
    .din28(j_mid2_reg_1140),
    .dout(tmp_9_fu_1065_p30)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_987_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_954 <= indvar_flatten_next_fu_993_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_954 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_1131 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_reg_965 <= j_mid2_reg_1140;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        j_reg_965 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_987_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_reg_976 <= k_1_fu_1059_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        k_reg_976 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_1131 <= exitcond_flatten_fu_987_p2;
        exitcond_flatten_reg_1131_pp0_iter1_reg <= exitcond_flatten_reg_1131;
        j_mid2_reg_1140_pp0_iter1_reg <= j_mid2_reg_1140;
        tmp_3_reg_1146_pp0_iter1_reg[4 : 0] <= tmp_3_reg_1146[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_987_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_mid2_reg_1140 <= j_mid2_fu_1019_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_fu_987_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_3_reg_1146[4 : 0] <= tmp_3_fu_1027_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_1131 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_9_reg_1323 <= tmp_9_fu_1065_p30;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd0) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_0_V_ce0 = 1'b1;
    end else begin
        activations_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_965)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_0_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_0_V_d0 = 48'd0;
        end else begin
            activations_0_V_d0 = 'bx;
        end
    end else begin
        activations_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd0) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_0_V_we0 = 1'b1;
    end else begin
        activations_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd10) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_10_V_ce0 = 1'b1;
    end else begin
        activations_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_968)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_10_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_10_V_d0 = 48'd0;
        end else begin
            activations_10_V_d0 = 'bx;
        end
    end else begin
        activations_10_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd10) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_10_V_we0 = 1'b1;
    end else begin
        activations_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd11) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_11_V_ce0 = 1'b1;
    end else begin
        activations_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_971)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_11_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_11_V_d0 = 48'd0;
        end else begin
            activations_11_V_d0 = 'bx;
        end
    end else begin
        activations_11_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd11) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_11_V_we0 = 1'b1;
    end else begin
        activations_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd12) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_12_V_ce0 = 1'b1;
    end else begin
        activations_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_974)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_12_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_12_V_d0 = 48'd0;
        end else begin
            activations_12_V_d0 = 'bx;
        end
    end else begin
        activations_12_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd12) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_12_V_we0 = 1'b1;
    end else begin
        activations_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd13) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_13_V_ce0 = 1'b1;
    end else begin
        activations_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_977)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_13_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_13_V_d0 = 48'd0;
        end else begin
            activations_13_V_d0 = 'bx;
        end
    end else begin
        activations_13_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd13) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_13_V_we0 = 1'b1;
    end else begin
        activations_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd14) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_14_V_ce0 = 1'b1;
    end else begin
        activations_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_980)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_14_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_14_V_d0 = 48'd0;
        end else begin
            activations_14_V_d0 = 'bx;
        end
    end else begin
        activations_14_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd14) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_14_V_we0 = 1'b1;
    end else begin
        activations_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd15) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_15_V_ce0 = 1'b1;
    end else begin
        activations_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_983)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_15_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_15_V_d0 = 48'd0;
        end else begin
            activations_15_V_d0 = 'bx;
        end
    end else begin
        activations_15_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd15) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_15_V_we0 = 1'b1;
    end else begin
        activations_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd16) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_16_V_ce0 = 1'b1;
    end else begin
        activations_16_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_986)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_16_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_16_V_d0 = 48'd0;
        end else begin
            activations_16_V_d0 = 'bx;
        end
    end else begin
        activations_16_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd16) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_16_V_we0 = 1'b1;
    end else begin
        activations_16_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd17) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_17_V_ce0 = 1'b1;
    end else begin
        activations_17_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_989)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_17_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_17_V_d0 = 48'd0;
        end else begin
            activations_17_V_d0 = 'bx;
        end
    end else begin
        activations_17_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd17) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_17_V_we0 = 1'b1;
    end else begin
        activations_17_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd18) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_18_V_ce0 = 1'b1;
    end else begin
        activations_18_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_992)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_18_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_18_V_d0 = 48'd0;
        end else begin
            activations_18_V_d0 = 'bx;
        end
    end else begin
        activations_18_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd18) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_18_V_we0 = 1'b1;
    end else begin
        activations_18_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd19) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_19_V_ce0 = 1'b1;
    end else begin
        activations_19_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_995)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_19_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_19_V_d0 = 48'd0;
        end else begin
            activations_19_V_d0 = 'bx;
        end
    end else begin
        activations_19_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd19) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_19_V_we0 = 1'b1;
    end else begin
        activations_19_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd1) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_1_V_ce0 = 1'b1;
    end else begin
        activations_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_998)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_1_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_1_V_d0 = 48'd0;
        end else begin
            activations_1_V_d0 = 'bx;
        end
    end else begin
        activations_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd1) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_1_V_we0 = 1'b1;
    end else begin
        activations_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd20) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_20_V_ce0 = 1'b1;
    end else begin
        activations_20_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1001)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_20_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_20_V_d0 = 48'd0;
        end else begin
            activations_20_V_d0 = 'bx;
        end
    end else begin
        activations_20_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd20) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_20_V_we0 = 1'b1;
    end else begin
        activations_20_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd21) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_21_V_ce0 = 1'b1;
    end else begin
        activations_21_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1004)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_21_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_21_V_d0 = 48'd0;
        end else begin
            activations_21_V_d0 = 'bx;
        end
    end else begin
        activations_21_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd21) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_21_V_we0 = 1'b1;
    end else begin
        activations_21_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd22) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_22_V_ce0 = 1'b1;
    end else begin
        activations_22_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1007)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_22_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_22_V_d0 = 48'd0;
        end else begin
            activations_22_V_d0 = 'bx;
        end
    end else begin
        activations_22_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd22) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_22_V_we0 = 1'b1;
    end else begin
        activations_22_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd23) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_23_V_ce0 = 1'b1;
    end else begin
        activations_23_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1010)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_23_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_23_V_d0 = 48'd0;
        end else begin
            activations_23_V_d0 = 'bx;
        end
    end else begin
        activations_23_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd23) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_23_V_we0 = 1'b1;
    end else begin
        activations_23_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd24) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_24_V_ce0 = 1'b1;
    end else begin
        activations_24_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1013)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_24_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_24_V_d0 = 48'd0;
        end else begin
            activations_24_V_d0 = 'bx;
        end
    end else begin
        activations_24_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd24) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_24_V_we0 = 1'b1;
    end else begin
        activations_24_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd25) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_25_V_ce0 = 1'b1;
    end else begin
        activations_25_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1016)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_25_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_25_V_d0 = 48'd0;
        end else begin
            activations_25_V_d0 = 'bx;
        end
    end else begin
        activations_25_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd25) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_25_V_we0 = 1'b1;
    end else begin
        activations_25_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd26) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_26_V_ce0 = 1'b1;
    end else begin
        activations_26_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1019)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_26_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_26_V_d0 = 48'd0;
        end else begin
            activations_26_V_d0 = 'bx;
        end
    end else begin
        activations_26_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd26) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_26_V_we0 = 1'b1;
    end else begin
        activations_26_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd31)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd30)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd29)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd28)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd27)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((j_mid2_reg_1140_pp0_iter1_reg == 5'd31) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd30) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd29) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd28) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd27) & (tmp_4_fu_1126_p2 == 1'd0)))))) begin
        activations_27_V_ce0 = 1'b1;
    end else begin
        activations_27_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_861)) begin
            activations_27_V_d0 = tmp_9_reg_1323;
        end else if ((1'b1 == ap_condition_850)) begin
            activations_27_V_d0 = 48'd0;
        end else begin
            activations_27_V_d0 = 'bx;
        end
    end else begin
        activations_27_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd31)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd30)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd29)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd28)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd27)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (((j_mid2_reg_1140_pp0_iter1_reg == 5'd31) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd30) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd29) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd28) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd27) & (tmp_4_fu_1126_p2 == 1'd0)))))) begin
        activations_27_V_we0 = 1'b1;
    end else begin
        activations_27_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd2) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_2_V_ce0 = 1'b1;
    end else begin
        activations_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1026)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_2_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_2_V_d0 = 48'd0;
        end else begin
            activations_2_V_d0 = 'bx;
        end
    end else begin
        activations_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd2) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_2_V_we0 = 1'b1;
    end else begin
        activations_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd3) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_3_V_ce0 = 1'b1;
    end else begin
        activations_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1029)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_3_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_3_V_d0 = 48'd0;
        end else begin
            activations_3_V_d0 = 'bx;
        end
    end else begin
        activations_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd3) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_3_V_we0 = 1'b1;
    end else begin
        activations_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd4) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_4_V_ce0 = 1'b1;
    end else begin
        activations_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1032)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_4_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_4_V_d0 = 48'd0;
        end else begin
            activations_4_V_d0 = 'bx;
        end
    end else begin
        activations_4_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd4) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_4_V_we0 = 1'b1;
    end else begin
        activations_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd5) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_5_V_ce0 = 1'b1;
    end else begin
        activations_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1035)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_5_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_5_V_d0 = 48'd0;
        end else begin
            activations_5_V_d0 = 'bx;
        end
    end else begin
        activations_5_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd5) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_5_V_we0 = 1'b1;
    end else begin
        activations_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd6) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_6_V_ce0 = 1'b1;
    end else begin
        activations_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1038)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_6_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_6_V_d0 = 48'd0;
        end else begin
            activations_6_V_d0 = 'bx;
        end
    end else begin
        activations_6_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd6) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_6_V_we0 = 1'b1;
    end else begin
        activations_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd7) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_7_V_ce0 = 1'b1;
    end else begin
        activations_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1041)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_7_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_7_V_d0 = 48'd0;
        end else begin
            activations_7_V_d0 = 'bx;
        end
    end else begin
        activations_7_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd7) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_7_V_we0 = 1'b1;
    end else begin
        activations_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd8) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_8_V_ce0 = 1'b1;
    end else begin
        activations_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1044)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_8_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_8_V_d0 = 48'd0;
        end else begin
            activations_8_V_d0 = 'bx;
        end
    end else begin
        activations_8_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd8) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_8_V_we0 = 1'b1;
    end else begin
        activations_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd9) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_9_V_ce0 = 1'b1;
    end else begin
        activations_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1047)) begin
        if ((tmp_4_fu_1126_p2 == 1'd1)) begin
            activations_9_V_d0 = tmp_9_reg_1323;
        end else if ((tmp_4_fu_1126_p2 == 1'd0)) begin
            activations_9_V_d0 = 48'd0;
        end else begin
            activations_9_V_d0 = 'bx;
        end
    end else begin
        activations_9_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd9) & (tmp_4_fu_1126_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        activations_9_V_we0 = 1'b1;
    end else begin
        activations_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_987_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_flatten_reg_1131 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_j_phi_fu_969_p4 = j_mid2_reg_1140;
    end else begin
        ap_phi_mux_j_phi_fu_969_p4 = j_reg_965;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_0_V_ce0 = 1'b1;
    end else begin
        in_features_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_10_V_ce0 = 1'b1;
    end else begin
        in_features_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_11_V_ce0 = 1'b1;
    end else begin
        in_features_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_12_V_ce0 = 1'b1;
    end else begin
        in_features_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_13_V_ce0 = 1'b1;
    end else begin
        in_features_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_14_V_ce0 = 1'b1;
    end else begin
        in_features_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_15_V_ce0 = 1'b1;
    end else begin
        in_features_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_16_V_ce0 = 1'b1;
    end else begin
        in_features_16_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_17_V_ce0 = 1'b1;
    end else begin
        in_features_17_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_18_V_ce0 = 1'b1;
    end else begin
        in_features_18_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_19_V_ce0 = 1'b1;
    end else begin
        in_features_19_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_1_V_ce0 = 1'b1;
    end else begin
        in_features_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_20_V_ce0 = 1'b1;
    end else begin
        in_features_20_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_21_V_ce0 = 1'b1;
    end else begin
        in_features_21_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_22_V_ce0 = 1'b1;
    end else begin
        in_features_22_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_23_V_ce0 = 1'b1;
    end else begin
        in_features_23_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_24_V_ce0 = 1'b1;
    end else begin
        in_features_24_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_25_V_ce0 = 1'b1;
    end else begin
        in_features_25_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_26_V_ce0 = 1'b1;
    end else begin
        in_features_26_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_27_V_ce0 = 1'b1;
    end else begin
        in_features_27_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_2_V_ce0 = 1'b1;
    end else begin
        in_features_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_3_V_ce0 = 1'b1;
    end else begin
        in_features_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_4_V_ce0 = 1'b1;
    end else begin
        in_features_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_5_V_ce0 = 1'b1;
    end else begin
        in_features_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_6_V_ce0 = 1'b1;
    end else begin
        in_features_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_7_V_ce0 = 1'b1;
    end else begin
        in_features_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_8_V_ce0 = 1'b1;
    end else begin
        in_features_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_features_9_V_ce0 = 1'b1;
    end else begin
        in_features_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_flatten_fu_987_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_flatten_fu_987_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign activations_0_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_10_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_11_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_12_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_13_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_14_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_15_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_16_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_17_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_18_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_19_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_1_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_20_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_21_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_22_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_23_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_24_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_25_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_26_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_27_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_2_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_3_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_4_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_5_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_6_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_7_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_8_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign activations_9_V_address0 = tmp_3_reg_1146_pp0_iter1_reg;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1001 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd20) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1004 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd21) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1007 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd22) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1010 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd23) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1013 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd24) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1016 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd25) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1019 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd26) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1026 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd2) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1029 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd3) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1032 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd4) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1035 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd5) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1038 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd6) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1041 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd7) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1044 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd8) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_1047 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd9) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_850 = (((j_mid2_reg_1140_pp0_iter1_reg == 5'd31) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd30) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd29) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd28) & (tmp_4_fu_1126_p2 == 1'd0)) | ((j_mid2_reg_1140_pp0_iter1_reg == 5'd27) & (tmp_4_fu_1126_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_861 = (((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd31)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd30)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd29)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd28)) | ((tmp_4_fu_1126_p2 == 1'd1) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd27)));
end

always @ (*) begin
    ap_condition_965 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_968 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd10) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_971 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd11) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_974 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd12) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_977 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd13) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_980 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd14) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_983 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd15) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_986 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd16) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_989 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd17) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_992 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd18) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_995 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd19) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_998 = ((1'b0 == ap_block_pp0_stage0) & (j_mid2_reg_1140_pp0_iter1_reg == 5'd1) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond_flatten_fu_987_p2 = ((indvar_flatten_reg_954 == 10'd784) ? 1'b1 : 1'b0);

assign in_features_0_V_address0 = tmp_3_fu_1027_p1;

assign in_features_10_V_address0 = tmp_3_fu_1027_p1;

assign in_features_11_V_address0 = tmp_3_fu_1027_p1;

assign in_features_12_V_address0 = tmp_3_fu_1027_p1;

assign in_features_13_V_address0 = tmp_3_fu_1027_p1;

assign in_features_14_V_address0 = tmp_3_fu_1027_p1;

assign in_features_15_V_address0 = tmp_3_fu_1027_p1;

assign in_features_16_V_address0 = tmp_3_fu_1027_p1;

assign in_features_17_V_address0 = tmp_3_fu_1027_p1;

assign in_features_18_V_address0 = tmp_3_fu_1027_p1;

assign in_features_19_V_address0 = tmp_3_fu_1027_p1;

assign in_features_1_V_address0 = tmp_3_fu_1027_p1;

assign in_features_20_V_address0 = tmp_3_fu_1027_p1;

assign in_features_21_V_address0 = tmp_3_fu_1027_p1;

assign in_features_22_V_address0 = tmp_3_fu_1027_p1;

assign in_features_23_V_address0 = tmp_3_fu_1027_p1;

assign in_features_24_V_address0 = tmp_3_fu_1027_p1;

assign in_features_25_V_address0 = tmp_3_fu_1027_p1;

assign in_features_26_V_address0 = tmp_3_fu_1027_p1;

assign in_features_27_V_address0 = tmp_3_fu_1027_p1;

assign in_features_2_V_address0 = tmp_3_fu_1027_p1;

assign in_features_3_V_address0 = tmp_3_fu_1027_p1;

assign in_features_4_V_address0 = tmp_3_fu_1027_p1;

assign in_features_5_V_address0 = tmp_3_fu_1027_p1;

assign in_features_6_V_address0 = tmp_3_fu_1027_p1;

assign in_features_7_V_address0 = tmp_3_fu_1027_p1;

assign in_features_8_V_address0 = tmp_3_fu_1027_p1;

assign in_features_9_V_address0 = tmp_3_fu_1027_p1;

assign indvar_flatten_next_fu_993_p2 = (indvar_flatten_reg_954 + 10'd1);

assign j_1_fu_999_p2 = (ap_phi_mux_j_phi_fu_969_p4 + 5'd1);

assign j_mid2_fu_1019_p3 = ((tmp_5_fu_1005_p2[0:0] === 1'b1) ? j_1_fu_999_p2 : ap_phi_mux_j_phi_fu_969_p4);

assign k_1_fu_1059_p2 = (k_mid2_fu_1011_p3 + 5'd1);

assign k_mid2_fu_1011_p3 = ((tmp_5_fu_1005_p2[0:0] === 1'b1) ? 5'd0 : k_reg_976);

assign tmp_3_fu_1027_p1 = k_mid2_fu_1011_p3;

assign tmp_4_fu_1126_p2 = (($signed(tmp_9_reg_1323) > $signed(48'd0)) ? 1'b1 : 1'b0);

assign tmp_5_fu_1005_p2 = ((k_reg_976 == 5'd28) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_3_reg_1146[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    tmp_3_reg_1146_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //relu
